apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pixta-job-ltr-send-messages-sqs
  labels:
    app: pixta-job-ltr-send-messages-sqs
    stage: staging
spec:
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: pixta-job-ltr-send-messages-sqs
            stage: staging
        spec:
          containers:
            - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ltr-data-serverless:staging
              name: job-ltr-send-messages-sqs
  schedule: "0 6 * * *"
  suspend: true

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ltr-job-get-data
  labels:
    app: ltr-job-get-data
    stage: staging
spec:
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: ltr-job-get-data
            stage: staging
        spec:
          containers:
            - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ltr-online-learning:staging
              name: job-ltr-get-data
              resources: {}
  schedule: "0 17 28 * *"
  suspend: false

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ltr-job-training-model
  labels:
    app: ltr-job-training-model
    stage: staging
spec:
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: ltr-job-training-model
            stage: staging
        spec:
          containers:
            - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ltr-online-learning:staging
              name: job-ltr-training-model

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ltr-job-evaluation
  labels:
    app: ltr-job-evaluation
    stage: staging
spec:
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: ltr-job-evaluation
            stage: staging
        spec:
          containers:
            - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ltr-online-learning:staging
              name: job-ltr-evaluation
