apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-highscore
  labels:
    app: image-highscore
    stage: staging
    tags.datadoghq.com/env: "staging"
    tags.datadoghq.com/service: "image-highscore"
    tags.datadoghq.com/version: "0.34.0"
spec:
  selector:
    matchLabels:
      app: image-highscore
      stage: staging
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
      labels:
        app: image-highscore
        stage: staging
        tags.datadoghq.com/env: "staging"
        tags.datadoghq.com/service: "image-highscore"
        tags.datadoghq.com/version: "0.34.0"
    spec:
      initContainers:
        - name: init-ckpt
          image: public.ecr.aws/bitnami/aws-cli:latest
          command:
            [
              "/bin/sh",
              "-c",
              "aws s3 sync --delete 's3://machine-learning-storage-stg/clearml/Image Highscore/convert_to_onnx.2afaf91b6f264c949f87b8c03af8f3fa/models/' /tmp/ckpt/",
            ]
          volumeMounts:
            - mountPath: /tmp/ckpt
              name: image-highscore-ckpt-vol
        - name: init-tagemb
          image: public.ecr.aws/bitnami/aws-cli:latest
          command:
            [
              "/bin/sh",
              "-c",
              "aws s3 sync --delete s3://machine-learning-storage-stg/h4i/tagemb/ /tmp/tagemb/",
            ]
          volumeMounts:
            - mountPath: /tmp/tagemb
              name: image-highscore-tagemb-vol
      containers:
        - name: image-highscore
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/lab-highscore-image:stg-1f5ef8a
          volumeMounts:
            - name: image-highscore-ckpt-vol
              mountPath: /projects/pixta_image_highscore/ckpt
            - name: image-highscore-tagemb-vol
              mountPath: /root/vocab-v4.pkl
              subPath: vocab-v4.pkl
            - name: image-highscore-tagemb-vol
              mountPath: /root/ckpt-v4-294252.h5
              subPath: ckpt-v4-294252.h5
