---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-tool-abort-checks
  labels:
    app: check-tool-abort-checks
    stage: staging
spec:
  replicas: 0
  selector:
    matchLabels:
      app: check-tool-abort-checks
      stage: staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::045675425505:role/stg-pixta-check-tool
      labels:
        app: check-tool-abort-checks
        stage: staging

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-tool-close-sending-check-result
  labels:
    app: check-tool-close-sending-check-result
    stage: staging
spec:
  replicas: 0
  selector:
    matchLabels:
      app: check-tool-close-sending-check-result
      stage: staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: check-tool-close-sending-check-result
        stage: staging
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::045675425505:role/stg-pixta-check-tool

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-tool-create-check-items
  labels:
    app: check-tool-create-check-items
    stage: staging
spec:
  replicas: 0
  selector:
    matchLabels:
      app: check-tool-create-check-items
      stage: staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: check-tool-create-check-items
        stage: staging
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::045675425505:role/stg-pixta-check-tool
