apiVersion: v1
kind: Secret
metadata:
    name: ife-secret
stringData:
    ROLLBAR_ACCESS_TOKEN: ENC[AES256_GCM,data:qahjZAiy/BuYaWVIwFLjLEy9m35+8SqVB29/Y1VUk4M=,iv:/3eJxX67/Jlluj1Dz2p/SV8jNULSrrc43YbzzGsT2dw=,tag:YrKW7DObX2S9ZmDdb1YFAA==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:045675425505:key/97008896-549e-41e0-ac53-58069a992bec
          created_at: "2021-07-15T06:39:52Z"
          enc: AQICAHhuUCqBQXMCkUJlXaKih1U3DC5iUw0PEuanKcAmzvfX3gEuf2ddX/lKGrs289O2xp0mAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCZaibjsJ0ibmcm5CAgEQgDvAJUPeK9crSi6v8H6rSsc7L++lWlOvc80asQY/fZ/O8l+S1hT4nHxP+bqmPAiLmrGm1M2tuMgvKZaZrA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-15T06:39:53Z"
    mac: ENC[AES256_GCM,data:PHIo3BWjzNd4S4+wr9XHzYI/m4tLKponr89SwxyFVy6bu5ga9RykyUMxH9nc1uGIBZii8ocXMOKyQueeERsLCg0WuENs7I2ITJL9aYwPGp0iYSW/6U9PvhmpdW4JeOZgQpv1iKH9NuxenMtmtDhBKi+NNYc4qp4L4idUOVbcPSs=,iv:6O9d7X0xU/Q8zJZTjdYBLLwkmwbo9pWtFurCYKUTf1I=,tag:ZVu2lJRJ5xQcNlBdMi2KZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
