apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pixta-job-post-chatwork
  labels:
    app: pixta-job-post-chatwork
    stage: staging
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: pixta-job-post-chatwork
            stage: staging
        spec:
          containers:
            - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/editor-api:staging
              imagePullPolicy: Always
              name: job-post-chatwork
  schedule: "5 0 * * *"
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 3
  suspend: true

# ---
# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: pixta-job-update-editor-data
#   labels:
#     app: pixta-job-update-editor-data
#     stage: staging
# spec:
#   suspend: true
#   jobTemplate:
#     spec:
#       backoffLimit: 0
#       template:
#         metadata:
#           annotations:
#             iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
#           labels:
#             app: pixta-job-update-editor-data
#             stage: staging
#         spec:
#           restartPolicy: Never
#           containers:
#             - image: 567351176096.dkr.ecr.ap-northeast-1.amazonaws.com/stg-pixta-app:master
#               name: job-update-editor-data
