apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-dictionaries
  labels:
    app: simple-dictionaries
spec:
  selector:
    matchLabels:
      app: simple-dictionaries
  template:
    metadata:
      labels:
        app: simple-dictionaries
    spec:
      volumes:
        - emptyDir: {}
          name: app
        - configMap:
            name: simple-dictionaries-web-config
          name: web-conf
      initContainers:
        # Nodejs Container
        - name: simple-dictionaries-app
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/simple-dictionaries:latest
          imagePullPolicy: Always
          command:
            - sh
            - -c
          args:
            - cp -pR ${NODE_ROOT}/build /app/public
          volumeMounts:
            - mountPath: /app
              name: app
          envFrom:
            - configMapRef:
                name: simple-dictionaries-application-env
      containers:
        - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:stable
          name: simple-dictionaries-nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 30Mi
          volumeMounts:
            - mountPath: /app
              name: app
            - mountPath: /config
              name: web-conf
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 30
            successThreshold: 1
            periodSeconds: 30
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 30
            successThreshold: 1
            periodSeconds: 30
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - rm -f /etc/nginx/conf.d/default.conf
                    && envsubst "$(env | awk -F = '{printf " $%s", $1}')" < /config/simple-dictionaries.conf > /etc/nginx/conf.d/simple-dictionaries.conf
                    && cp -pf /config/nginx.conf /etc/nginx/nginx.conf && nginx -s reload
            preStop:
              exec:
                command:
                  - /usr/sbin/nginx
                  - -s
                  - quit
