apiVersion: v1
kind: Service
metadata:
  name: simple-dictionaries-svc
spec:
  selector:
    app: simple-dictionaries
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
