apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pixta-job-ltr-send-messages-sqs
  labels:
    app: pixta-job-ltr-send-messages-sqs
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: pixta-job-ltr-send-messages-sqs
        spec:
          restartPolicy: Never
          containers:
            - envFrom:
                - configMapRef:
                    name: ltr-common-env
                    optional: false
                - secretRef:
                    name: ltr-secret
                    optional: false
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ltr-data-serverless:latest
              imagePullPolicy: Always
              name: job-ltr-send-messages-sqs
          terminationGracePeriodSeconds: 30
  schedule: "0 6 * * *"
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 4

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ltr-job-get-data
  labels:
    app: ltr-job-get-data
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      labels:
        app: ltr-job-get-data
    spec:
      backoffLimit: 2
      template:
        spec: 
          restartPolicy: Never
          containers:
            - envFrom:
                - configMapRef:
                    name: ltr-online-learning-common-env
                - secretRef:
                    name: ltr-secret
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ltr-online-learning:latest
              imagePullPolicy: Always
              name: job-ltr-get-data
              #resources:
              #  requests:
              #    memory: "12Gi"
              #    cpu: "1200m"
              #  limits:
              #    cpu: "1200m"
              #    memory: "12Gi"
  schedule: "0 8 * * *"
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 4
  suspend: false

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ltr-job-training-model
  labels:
    app: ltr-job-training-model
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      labels:
        app: ltr-job-training-model
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - args:
                - -c
                - cd model_trainer && chmod +x ./model_train.sh && ./model_train.sh
              command:
                - /bin/bash
              envFrom:
                - configMapRef:
                    name: ltr-online-learning-common-env
                - secretRef:
                    name: ltr-secret
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ltr-online-learning:latest
              imagePullPolicy: Always
              name: job-ltr-training-model
              resources:
                requests:
                  memory: "12Gi"
                  cpu: "1200m"
                limits:
                  cpu: "1200m"
                  memory: "12Gi"
  schedule: "0 0 29 2 *"
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 4
  suspend: true

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ltr-job-evaluation
  labels:
    app: ltr-job-evaluation
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      labels:
        app: ltr-job-evaluation
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - args:
                - -c
                - cd evaluation && python evaluation.py
              command:
                - /bin/bash
              envFrom:
                - configMapRef:
                    name: ltr-online-learning-common-env
                - secretRef:
                    name: ltr-secret
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ltr-online-learning:latest
              imagePullPolicy: Always
              name: job-ltr-evaluation
              resources:
                requests:
                  memory: "12Gi"
                  cpu: "1200m"
                limits:
                  cpu: "1200m"
                  memory: "12Gi"
  schedule: "0 0 29 2 *"
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 4
  suspend: true
