apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pixta-job-ltr-model-pipeline
  labels:
    app: pixta-job-ltr-model-pipeline
    stage: production
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: pixta-job-ltr-model-pipeline
            stage: production
        spec:
          nodeSelector:
            lab-worker: "true"
          containers:
            - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/lab-ltrv2-model-pipeline:v1.1.5
              name: job-ltr-model-pipeline
          restartPolicy: "Never"
