apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pixta-job-ltr-model-pipeline
  labels:
    app: pixta-job-ltr-model-pipeline
spec:
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pixta-job-ltr-model-pipeline
        spec:
          containers:
            - envFrom:
                - configMapRef:
                    name: ltr-common-env
                    optional: false
                - secretRef:
                    name: ltr-secret
                    optional: false
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/lab-ltrv2-model-pipeline:latest
              imagePullPolicy: Always
              name: job-ltr-model-pipeline
              command: ["/bin/sh", "-c", "./main.sh"]
              resources:
                requests:
                  cpu: 4000m
                  memory: 20Gi
                limits:
                  cpu: 4000m
                  memory: 20Gi
  schedule: "0 0 1 */6 *"
