apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfm-checktool-result-poller
  labels:
    app: pfm-checktool-result-poller
spec:
  selector:
    matchLabels:
      app: pfm-checktool-result-poller
  template:
    metadata:
      labels:
        app: pfm-checktool-result-poller
    spec:
      nodeSelector:
        balance-spot-public-instance: "true"
      tolerations:
        - key: "balance-spot-public-instance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: pfm-checktool-result-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:latest
          imagePullPolicy: Always
          command:
            [
              "bash",
              "-c",
              "bin/rails runner 'Batch::ChecktoolResultQueue.new.run'",
            ]
          envFrom:
            - secretRef:
                name: pfm-secret
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfm-checktool-start-poller
  labels:
    app: pfm-checktool-start-poller
spec:
  selector:
    matchLabels:
      app: pfm-checktool-start-poller
  template:
    metadata:
      labels:
        app: pfm-checktool-start-poller
    spec:
      nodeSelector:
        balance-spot-public-instance: "true"
      tolerations:
        - key: "balance-spot-public-instance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: pfm-checktool-start-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:latest
          imagePullPolicy: Always
          command:
            [
              "bash",
              "-c",
              "bin/rails runner 'Batch::ChecktoolStartQueue.new.run'",
            ]
          envFrom:
            - secretRef:
                name: pfm-secret
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfm-product-poller
  labels:
    app: pfm-product-poller
spec:
  selector:
    matchLabels:
      app: pfm-product-poller
  template:
    metadata:
      labels:
        app: pfm-product-poller
    spec:
      nodeSelector:
        balance-spot-public-instance: "true"
      tolerations:
        - key: "balance-spot-public-instance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: pfm-product-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:latest
          imagePullPolicy: Always
          command:
            ["bash", "-c", "bin/rails runner 'Batch::ProductQueue.new.run'"]
          envFrom:
            - secretRef:
                name: pfm-secret
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfm-tag-poller
  labels:
    app: pfm-tag-poller
spec:
  selector:
    matchLabels:
      app: pfm-tag-poller
  template:
    metadata:
      labels:
        app: pfm-tag-poller
    spec:
      nodeSelector:
        balance-spot-public-instance: "true"
      tolerations:
        - key: "balance-spot-public-instance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: pfm-tag-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:latest
          imagePullPolicy: Always
          command: ["bash", "-c", "bin/rails runner 'Batch::TagQueue.new.run'"]
          envFrom:
            - secretRef:
                name: pfm-secret
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfm-thumbnail-poller
  labels:
    app: pfm-thumbnail-poller
spec:
  selector:
    matchLabels:
      app: pfm-thumbnail-poller
  template:
    metadata:
      labels:
        app: pfm-thumbnail-poller
    spec:
      nodeSelector:
        balance-spot-public-instance: "true"
      tolerations:
        - key: "balance-spot-public-instance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: pfm-thumbnail-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:latest
          imagePullPolicy: Always
          command:
            ["bash", "-c", "bin/rails runner 'Batch::ThumbnailQueue.new.run'"]
          envFrom:
            - secretRef:
                name: pfm-secret
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfm-auto-tag-result-poller
  labels:
    app: pfm-auto-tag-result-poller
spec:
  selector:
    matchLabels:
      app: pfm-auto-tag-result-poller
  template:
    metadata:
      labels:
        app: pfm-auto-tag-result-poller
    spec:
      nodeSelector:
        balance-spot-public-instance: "true"
      tolerations:
        - key: "balance-spot-public-instance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: pfm-auto-tag-result-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:latest
          imagePullPolicy: Always
          command:
            [
              "bash",
              "-c",
              "bin/rails runner 'Batch::AutoCheckTagResult.new.run'",
            ]
          envFrom:
            - secretRef:
                name: pfm-secret
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfm-ra-poller
  labels:
    app: pfm-ra-poller
spec:
  selector:
    matchLabels:
      app: pfm-ra-poller
  template:
    metadata:
      labels:
        app: pfm-ra-poller
    spec:
      nodeSelector:
        balance-spot-public-instance: "true"
      tolerations:
        - key: "balance-spot-public-instance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: pfm-ra-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:latest
          imagePullPolicy: Always
          command:
            ["bash", "-c", "bin/rails runner 'Batch::FetchRaInfo.new.run'"]
          envFrom:
            - secretRef:
                name: pfm-secret
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
