apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffm-delayed-job
  labels:
    app: ffm-delayed-job
spec:
  selector:
    matchLabels:
      app: ffm-delayed-job
  template:
    metadata:
      labels:
        app: ffm-delayed-job
    spec:
      containers:
      - name: ffm-delayed-job
        image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ffm_app:latest
        imagePullPolicy: Always
        command: ["bash", "-c", "rake jobs:work"]
        envFrom:
        - secretRef:
            name: ffm-secret
        - configMapRef:
            name: ffm-common-env  
        resources:
          requests:
            memory: "230Mi"
            cpu: "20m"
          limits:
            memory: "460Mi"
            cpu: "50m"
