resources:
  - deployment.yaml
  - service.yaml
  - delayed_job.yaml
  - cronjob.yaml
  - polling.yaml
configMapGenerator:
  - name: ffm-common-env
    literals:
     - RAILS_ROOT=/var/www/footage-flow-manager
  - name: ffm-nginx-conf
    files:
      - configmap/nginx.conf
      - configmap/pixta-ffm.conf
  - name: ffm-unicorn-rb
    files:
      - configmap/unicorn.rb
generatorOptions: 
  disableNameSuffixHash: true 
