apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pixta-job-ltr-send-messages-sqs
  labels:
    app: pixta-job-ltr-send-messages-sqs
    stage: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: pixta-job-ltr-send-messages-sqs
            stage: production
        spec:
          restartPolicy: Never
          containers:
            - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ltr-data-serverless:production
              name: job-ltr-send-messages-sqs
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "500m"
                limits:
                  memory: "4Gi"
  schedule: "0 6 * * *"
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 4

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ltr-job-get-data
  labels:
    app: ltr-job-get-data
    stage: production
spec:
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: ltr-job-get-data
            stage: production
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: eks.amazonaws.com/capacityType
                        operator: In
                        values:
                          - ON_DEMAND
                  weight: 10
          containers:
            - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ltr-online-learning:production
              name: job-ltr-get-data
          priorityClassName: system-node-critical
  schedule: "10 8 * * 1"
  suspend: true

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ltr-job-training-model
  labels:
    app: ltr-job-training-model
    stage: production
spec:
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: ltr-job-training-model
            stage: production
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: eks.amazonaws.com/capacityType
                        operator: In
                        values:
                          - ON_DEMAND
                  weight: 10
          containers:
            - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ltr-online-learning:production
              name: job-ltr-training-model

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ltr-job-evaluation
  labels:
    app: ltr-job-evaluation
    stage: production
spec:
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: ltr-job-evaluation
            stage: production
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: eks.amazonaws.com/capacityType
                        operator: In
                        values:
                          - ON_DEMAND
                  weight: 10
          containers:
            - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/ltr-online-learning:production
              name: job-ltr-evaluation
