apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-pcc
  labels:
    app: lab-pcc
    stage: staging
spec:
  selector:
    matchLabels:
      app: lab-pcc
      stage: staging
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
      labels:
        app: lab-pcc
        stage: staging

