apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-pcc
  labels:
    app: lab-pcc
spec:
  selector:
    matchLabels:
      app: lab-pcc
  template:
    metadata:
      labels:
        app: lab-pcc
    spec:
      tolerations:
        - key: "spotInstance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      volumes:
        - name: pcc-data-vol
          persistentVolumeClaim:
            claimName: pcc-data-pvc
        - name: pcc-ckpts-vol
          persistentVolumeClaim:
            claimName: pcc-ckpts-pvc
      initContainers:
        - name: init-data
          image: xueshanf/awscli:latest
          command:
            [
              "/bin/sh",
              "-c",
              "aws s3 sync --delete s3://machine-learning-storage-stg/pcc/v3/ckpts/ /tmp/ckpts/",
            ]
          volumeMounts:
            - mountPath: /tmp/ckpts
              name: pcc-ckpts-vol
        - name: init-models
          image: xueshanf/awscli:latest
          command:
            [
              "/bin/sh",
              "-c",
              "aws s3 sync --delete s3://machine-learning-storage-stg/pcc/v3/data/ /tmp/data/",
            ]
          volumeMounts:
            - mountPath: /tmp/data
              name: pcc-data-vol
      containers:
        - name: lab-pcc
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/lab-pcc:v3.5.5
          imagePullPolicy: Always
          command:
            - "python3"
          args:
            - "main.py"
          resources:
            requests:
              memory: "1.2Gi"
              cpu: "785m"
            limits:
              memory: "2Gi"
              cpu: "1570m"
          volumeMounts:
            - name: pcc-data-vol
              mountPath: /pcc_v3/data/model_p.txt
              subPath: model_p.txt
            - name: pcc-ckpts-vol
              mountPath: /pcc_v3/src/trained_models/DeepSet_300_Parallel/DeepSet_300_Parallel.pth
              subPath: DeepSet_300_Parallel_final.pth
