apiVersion: apps/v1
kind: Deployment
metadata:
  name: tag-suggestion
  labels:
    app: tag-suggestion
spec:
  selector:
    matchLabels:
      app: tag-suggestion
  template:
    metadata:
      labels:
        app: tag-suggestion
    spec:
      tolerations:
        - key: "spotInstance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      volumes:
        - configMap:
            name: tag-suggestion-web-conf
          name: web-conf
        - name: tag-ckpt-vol
          persistentVolumeClaim:
            claimName: tag-ckpt-pvc-1
        - configMap:
            name: tag-suggestion-conf
          name: tag-conf
      initContainers:
        - name: init-ckpt
          image: xueshanf/awscli:latest
          command:
            [
              "/bin/sh",
              "-c",
              "aws s3 sync --delete s3://machine-learning-storage-stg/tag-suggestion/version2/multilabel_classifier/ckpt/ /tmp/ckpt/",
            ]
          volumeMounts:
            - mountPath: /tmp/ckpt
              name: tag-ckpt-vol
      containers:
        - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:stable
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
          envFrom:
            - configMapRef:
                name: tag-suggestion-nginx-env
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: web-conf
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - rm -f /etc/nginx/conf.d/default.conf
                    && envsubst "$(env | awk -F = '{printf " $%s", $1}')" < /config/tag-suggestion.conf > /etc/nginx/conf.d/tag-suggestion.conf
                    && cp -pf /config/nginx.conf /etc/nginx/nginx.conf && nginx -s reload
            preStop:
              exec:
                command:
                  - /usr/sbin/nginx
                  - -s
                  - quit
        - name: tag-suggestion
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/lab-tag-suggestion:2.1.1.1
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "~/.local/bin/gunicorn --bind 0.0.0.0:8000 --workers=1 --max-requests 1500 -- wsgi:app",
            ]
          livenessProbe:
            failureThreshold: 5
            successThreshold: 1
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 30
            periodSeconds: 60
          readinessProbe:
            successThreshold: 1
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 30
            periodSeconds: 60
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "2.1Gi"
              cpu: "100m"
            limits:
              memory: "4Gi"
          envFrom:
            - secretRef:
                name: tag-suggestion-secret
                optional: false
          volumeMounts:
            - name: tag-conf
              mountPath: /ts_multilabel_classifier/config/inference.yml
              subPath: inference.yml
            - name: tag-ckpt-vol
              mountPath: /ts_multilabel_classifier/ckpt
