resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
configMapGenerator:
  - name: tag-suggestion-web-conf
    files:
      - configmap/nginx.conf
generatorOptions: 
  disableNameSuffixHash: false 
