bases:
  - ../../../../base/item-flow/pixta-uploader
resources:
  - ingress.yaml
  - secret.yaml
configMapGenerator:
  - name: pixta-uploader-application-env
    behavior: merge
    literals:
      - DEPLOY_ENV=staging
      - REGION=ap-northeast-1
      - REQ_FIN_SQS=request-finish-upload-jp-stg
      - REDIS_HOST=stg-uploader-redis-jp.sfiycx.ng.0001.apne1.cache.amazonaws.com
  - name: pixta-uploader-nginx-env
    literals:
      - NGINX_HTTP_HOST="$http_host"
      - NGINX_RESOLVER_HOST="10.0.0.2"
      - NGINX_SERVER_NAME="upload-staging.pixta.jp upload-staging.pixtastock.com"
generatorOptions:
  disableNameSuffixHash: false
patchesStrategicMerge:
  - deployment_patch.yaml
  - service_patch.yaml
  - cronjob_patch.yaml
