apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pfm-new-cronjob
  labels:
    app: pfm-new-cronjob
    stage: production
spec:
  schedule: "0 * * * *"
  startingDeadlineSeconds: 180
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: pfm-new-cronjob
            stage: production
        spec:
          containers:
            - name: pfm-new-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:prod-744e4b9

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pfm-tag-cronjob
  labels:
    app: pfm-tag-cronjob
    stage: production
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: pfm-tag-cronjob
            stage: production
        spec:
          containers:
            - name: pfm-tag-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:prod-744e4b9

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pfm-thumbnail-cronjob
  labels:
    app: pfm-thumbnail-cronjob
    stage: production
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: pfm-thumbnail-cronjob
            stage: production
        spec:
          containers:
            - name: pfm-thumbnail-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:prod-744e4b9

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pfm-ra-cronjob
  labels:
    app: pfm-ra-cronjob
    stage: production
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: pfm-ra-cronjob
            stage: production
        spec:
          containers:
            - name: pfm-ra-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:prod-744e4b9

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pfm-review-ok-cronjob
  labels:
    app: pfm-review-ok-cronjob
    stage: production
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: pfm-review-ok-cronjob
            stage: production
        spec:
          containers:
            - name: pfm-review-ok-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:prod-744e4b9

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pfm-abort-cronjob
  labels:
    app: pfm-abort-cronjob
    stage: production
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: pfm-abort-cronjob
            stage: production
        spec:
          containers:
            - name: pfm-abort-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:prod-744e4b9

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pfm-update-result-cronjob
  labels:
    app: pfm-update-result-cronjob
    stage: production
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: pfm-update-result-cronjob
            stage: production
        spec:
          containers:
            - name: pfm-update-result-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:prod-744e4b9

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pfm-request-check-tag-cronjob
  labels:
    app: pfm-request-check-tag-cronjob
    stage: production
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: pfm-request-check-tag-cronjob
            stage: production
        spec:
          containers:
            - name: pfm-request-check-tag-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pfm_app:prod-d0b1bdb
