apiVersion: v1
data:
    AIRBRAKE_PROJECT_ID: ENC[AES256_GCM,data:FWIX/uO2GME=,iv:+sn7sopdiauvkoRXsKmpXA0+msgIauncr1aZf9o7xdI=,tag:OUKtB4sFXErJ0r4XZfYhkA==,type:str]
    AIRBRAKE_PROJECT_KEY: ENC[AES256_GCM,data:r+x/Vbjzcox/N+GYti8QgdAImihmtzTAKQ+2ETs1efQilceDBq8+P/MnxrM=,iv:WqLf438nYIFkjU9VHhCJjXiphb0qfwacxSVHHEa0/GY=,tag:OSVmQTCK33HygZ0Bhi3J/g==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:4LbU6Gbx6j9fjOkDydTrgdHEEbU=,iv:qkX6VwW+DdVlQXpiLDHYh4iVuUtRVQo6U/o3NGM6IyM=,tag:yIUuf9cUW+mad/3WD9FT4w==,type:str]
    DB_HOST: ENC[AES256_GCM,data:U8vN6jMSfxTQGibuouChOqZtSrkeqEEkflEFb83JqUhv8+lClF25/oEqqeoOSMjqXOKvoSNofvTqtkP3Lri11Y8W+6IKyyWssJgyq3wmNAEcFVq7OGZtaTwhkAbglkcg,iv:Vl9JKmQn6KpG/0aOqkDUx6MZB7g3UfJCeTzDOukBeHE=,tag:38G8SGSxV5lnLjg7t//XBQ==,type:str]
    DB_PASS: ENC[AES256_GCM,data:tcLbLslkOCaAGBU++Q4Cb/wUg0rQalsXXZvgLu608Ok4nL+YJj+fz1a4LKc=,iv:C4Ez9UqB9pZO8gCknOK20gUqMJqGNSnB8L8Mm5wCoNo=,tag:xXdBXsBi2A+nXsD4zA32VA==,type:str]
    DB_USER: ENC[AES256_GCM,data:IVHt8wgZqsjWzuWi,iv:mqFMFNFDdJ+m0p8mwy4uwQsKQKqQvqg7ZKkfGHT8p9U=,tag:yKFGipLSw9iFBhAbxQXYgw==,type:str]
    DELAYED_JOB_PROCESS_NUM: ENC[AES256_GCM,data:O/MXXg==,iv:qx8xo5V2z/hnOZmC7h8tv6X/EfZIbd+zoWGQQw2Xij0=,tag:dasboqYtri8nKpUVUlfIHg==,type:str]
    ELASTICSEARCH_GRANTED_USER: ENC[AES256_GCM,data:Fl6XEBIOdl78UYg+Ab7ObA==,iv:nHrNkZ3Ni5gkD7ThqU8P4WmyP+ffPj1pRLTDiqqgYaw=,tag:h8xt7g4VhG/prugH2xdOOg==,type:str]
    ELASTICSEARCH_HOST: ENC[AES256_GCM,data:xcz7cpSsw7VHgC4qoKw4jWKeR5q1d4ERCMRDyUalq1mlZxtjV3kDCMdfP19Tbua4qWwhWdQZsoO9ifFyetilM+ankgEaUzOX+Rl32Ia48+s=,iv:PKLXD0d0e5jqtaO37gutw6+gkQji1HCFvI+BkyLAn/E=,tag:csuCiI+2DJQe/0ttU3UEtA==,type:str]
    ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:dRZ3b+vtkU1eu7ZP4wtOJyCTBWrY/L1CGiC1+A==,iv:6b7a5gFxfmYncv/qw3Klr7RbHDCT6+JyHz5qEi/BDX4=,tag:8GRMMMyxfAcXyP9UHivn7w==,type:str]
    ELASTICSEARCH_PHOTO_INDEX: ENC[AES256_GCM,data:U+8PNhba36xEZv+f0K+NR3iWsLg=,iv:fNBjjmZJAYRUkKdzi/+m21gyiGeoKE7FmhekbhE9iXg=,tag:KD8be9ueGLlxtGnK8xCkQA==,type:str]
    ELASTICSEARCH_PHOTO_TYPE: ENC[AES256_GCM,data:prJK4odALM8PiK6J+TJ1Yw==,iv:QHP09tj//JX0gj4WF0GOeK6uofDkRJJopY83fab4JG8=,tag:a/DojcId3/kjUgVi0kN+kw==,type:str]
    ELASTICSEARCH_PORT: ENC[AES256_GCM,data:9largpFF5oc=,iv:J/kSjdiI4LNjunYW9c9gFvI/hk3hrORhhnkGAjg02h0=,tag:k3FuQI2z3ktTC+qYYWts1A==,type:str]
    PIXTA_TOKEN: ENC[AES256_GCM,data:KkZ2kQLVoTyfuYKvETl0bsputg/s1VlnqJbgFhCb553qZn663iAu6e5AENZqqxrQXjOfE3PBDM5pb+5usvWcd7+Y7EzkqAn/knZNgrkeublOv4s16vpDTQ==,iv:Lc8mp2EFrI41lLGX37M2i5fNvGdBUtLCS9iOUP3dJCQ=,tag:S8i2lZgffwjkB6Cj2PDsMw==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:s7kzxm3RheGBnIm6Z9fF/g==,iv:0D7VScvLZRxBrE1TFVmVwz5XY5eYgZWB+5gKEk9W6dQ=,tag:ZcPMhTla3I5kijXdE2pg5Q==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:6nsPD2LPKw4liexWaTk2Tiy4RIFr2zMGWo61HIfte0NZrHUyIKtrTgcNGB/ilU+NSab7qFiPv8z3gMpEY0EICR7/QGr44ic0n/ycuKALXyW9jN1kgIhEBUgc94l7Pt18T6YBXLWPFwqYWJyaqwAzdsWZIlIISCiASkhHsHn6Gebbm4+r8AMvT4yW22H/devt81zNBSlDLot0Am/ysrD+a2K5WqAN4mpZBVftLw==,iv:s80nT2PglvD3X5n6IEmykOhL5hTPtLieaywpoJx7pIE=,tag:Aw8OwaqiipDE3e27eAXL3w==,type:str]
    SLACK_NOTIFICATION_CHANNEL: ENC[AES256_GCM,data:uuuDP5JzJ++P8F7v5QI6gw==,iv:zDJZmtZ1zEdXkaONxfybF2B4quvHAd/9LNdnBpfEm3Q=,tag:q1VseUhvjCbKPZsAjhhe/A==,type:str]
    SLACK_NOTIFICATION_URL: ENC[AES256_GCM,data:oQekdY5EzpiCedkrhbE1h21Sait09/auUQ2MGU35F8nOqWRFcIJz9oUZE2MP8e/Tsy4QtSwtpgl2d8X7hdoHVpSH+QNHaOUJ2NFGmRB+Bv7TdXK/OuwkzSrVUwWPE5VMaxlfGz9K62s=,iv:o6dpd8TOy/adSC63foyNkXE2evAZZYXhKPZ2IYXETcA=,tag:hEfnmUAHkKcrKFIQbxBimw==,type:str]
    HOST_NAME: ENC[AES256_GCM,data:94ekv4s0tPHwyfEVwka1yK1fgDWDG0TeQEZ1rHN4oK0drSsQ4lGgyw==,iv:at/+vtNuLR0wZMZMsY0ggQNQR/vRLYdfIN6znnTY4eo=,tag:dnYl3HZH2muquNPJzzfoIw==,type:str]
    ROLLBAR_ACCESS_TOKEN: ENC[AES256_GCM,data:JlvXmM1aBxPJYzz89chya2zfRF3gFLATMkikFrybDUsqMsgSTMG/v6DeDgg=,iv:m7A30TxgEv+jn9GY1wc5h0KCdpvbK3nrvlgKbBlcEEQ=,tag:9wqP2i7EMeHeNQFwYR9fXQ==,type:str]
    ELASTICSEARCH_PHOTO_TYPE_PROCESS: ENC[AES256_GCM,data:5kJJXp6zEZc=,iv:VZXJtuSSiWLkm/A/ScacZ9GX2K627wD6+dOaBtw7xiQ=,tag:8tr37U2zF3NmpjPZoMBYhQ==,type:str]
    ELASTICSEARCH_PHOTO_INDEX_PROCESS: ENC[AES256_GCM,data:X4djudVIMIv41TpHS4N8/4HDuBvu948w,iv:UqxaaEboxIP3XQCRtZTb26Ond4huJxBc8zhF1fTlJZ4=,tag:l1IGKtLKWLrOtno9th/uGA==,type:str]
    ELASTICSEARCH_PHOTO_INDEX_DEBUG: ENC[AES256_GCM,data:tRwsleX9elU=,iv:aPWrLZgGEYniwh/oXIsGb6OR3QlDgVM7PaRUbEHVgOs=,tag:CXRirqhy2kk0TO1NBzFBQQ==,type:str]
    ELASTICSEARCH_PHOTO_TYPE_DEBUG: ENC[AES256_GCM,data:0LGVYeo9FH4=,iv:CH0MS9PK8aCxrcaR93RDU6ES9E47mYwu/8uAdycZLdg=,tag:VSiqvaXK6g0V6Lf42BVyeg==,type:str]
kind: Secret
metadata:
    name: pfm-secret
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:045675425505:key/97008896-549e-41e0-ac53-58069a992bec
          created_at: "2022-06-30T03:40:53Z"
          enc: AQICAHhuUCqBQXMCkUJlXaKih1U3DC5iUw0PEuanKcAmzvfX3gHruI3RBdwEpLPyY2VVSzpyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMO2kLXGcmhsUVu7KqAgEQgDtFoFXf/girnrQPYDDqYpSy+04VidmMPIuOhh3pTHxco97PYmdvlYSObk5ILAPOUWuT5ipmK/wtzNi19A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-30T03:40:54Z"
    mac: ENC[AES256_GCM,data:oj+XZHiXtTK5GKkZbqnXYJbubu32EQr77vLjWKcX8JKTImqKp7coftKqq5CvhxsrOxySfVXP8ndNnW/Me8rfll1hWJCImVlQOMIb+6wezxUZvZ4o+VOJT5hpAoErcnSMpW2m/LewzevydrER+J1kmNEqAO4dz/ZTMouMvkndHvE=,iv:nqXOfxbjeDnf4mVm8M/gj9AJZjzuNyPxp/LJaauIXcY=,tag:HjXQpoaLrpkcrcXWNGxOCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
