apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-png
  labels:
    app: worker-png
    stage: staging
spec:
  selector:
    matchLabels:
      app: worker-png
      stage: staging
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker-png
        stage: staging
    spec:
      containers:
        - name: worker-png
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/worker-png:stg-e40cd78
