apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-thumbnail-reserved
  labels:
    app: worker-thumbnail-reserved
spec:
  selector:
    matchLabels:
      app: worker-thumbnail-reserved
  template:
    metadata:
      labels:
        app: worker-thumbnail-reserved
    spec:
      containers:
        - name: worker-thumbnail-reserved
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/worker-thumbnail-reserved:prod-reserved-a0ff496
          imagePullPolicy: Always
          resources:
            limits:
              memory: "3Gi"
            requests:
              memory: "1Gi"
              cpu: "700m"
          envFrom:
            - configMapRef:
                name: worker-thumbnail-reserved-common-env
            - secretRef:
                name: worker-thumbnail-reserved-secret
