bases:
  - ../../../../base/customer/sendmail
resources:
  - ingress.yaml
  - secret.yaml
  # - scaledobject.yaml
configMapGenerator:
  - name: sendmail-application-env
    behavior: merge
    literals:
      - RAILS_ENV=production
      - UNICORN_WORKER_PROCESSES=4
      - SQS_TRACKING=https://sqs.ap-northeast-1.amazonaws.com/045675425505/tracking_sendmail_production
  - name: sendmail-nginx-env
    literals:
      - NGINX_HTTP_HOST="$http_host"
      - NGINX_SERVER_NAME="sendmail.pixtastock.com"
  - name: sendmail-web-config
    behavior: merge
    files:
      - configmap/sendmail.conf
  - name: sendmail-mail-config
    files:
      - configmap/main.cf
generatorOptions:
  disableNameSuffixHash: false
patchesStrategicMerge:
  - deployment_patch.yaml
  - service_patch.yaml
