apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-pcc
  labels:
    app: lab-pcc
    stage: production
  annotations:
    kube-score/ignore: container-resources,container-image-tag,deployment-has-poddisruptionbudget,deployment-has-host-podantiaffinity
spec:
  selector:
    matchLabels:
      app: lab-pcc
      stage: production
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
      labels:
        app: lab-pcc
        stage: production
    spec:
      nodeSelector:
        eks.amazonaws.com/capacityType: "ON_DEMAND"
      volumes:
        - configMap:
            items:
              - key: production.yaml
                path: config.yaml
            name: lab-pcc-conf
          name: pcc-conf
      containers:
        - name: lab-pcc
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/lab-pcc:v3.5.7
          volumeMounts:
            - mountPath: /pcc_v3/config/photo
              name: pcc-conf
