---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-fix-checks
  labels:
    app: check-tool-fix-checks
spec:
  schedule: "10,40 0-14 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-fix-checks-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::FixChecks.new.run"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-send-check-result1
  labels:
    app: check-tool-send-check-result1
spec:
  schedule: "0 18,20,22 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-send-check-result1-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::SendCheckResult.new.run"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-send-check-result2
  labels:
    app: check-tool-send-check-result2
spec:
  schedule: "20,50 0-14 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-send-check-result2-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::SendCheckResult.new.run"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-start-check-items1
  labels:
    app: check-tool-start-check-items1
spec:
  schedule: "0 17,19,21 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-start-check-items1-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::StartCheckItems.new.run"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-start-check-items2
  labels:
    app: check-tool-start-check-items2
spec:
  schedule: "28 0-14 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-start-check-items2-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::StartCheckItems.new.run"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-assign-checks1
  labels:
    app: check-tool-assign-checks1
spec:
  schedule: "40 16-17 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-assign-checks1-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::AssignChecks.run_all_queues"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-assign-checks2
  labels:
    app: check-tool-assign-checks2
spec:
  schedule: "40 19-23,0-14 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-assign-checks2-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::AssignChecks.run_all_queues"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-timeout-checks
  labels:
    app: check-tool-timeout-checks
spec:
  schedule: "0 * * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-timeout-checks-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::TimeoutChecks.new.run"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-counting-queue-items1
  labels:
    app: check-tool-counting-queue-items1
spec:
  schedule: "15,45 15,16 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-counting-queue-items1-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::CountingQueueItems.new.run"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-counting-queue-items2
  labels:
    app: check-tool-counting-queue-items2
spec:
  schedule: "*/15 17-23,0-14 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-counting-queue-items2-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::CountingQueueItems.new.run"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-count-daily-checks1
  labels:
    app: check-tool-count-daily-checks1
spec:
  schedule: "0 15 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-count-daily-checks1-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - '/usr/local/bin/ruby bin/rails runner "Batch::CountDailyChecks.new.run(target_date: Date.yesterday)"'
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-count-daily-checks2
  labels:
    app: check-tool-count-daily-checks2
spec:
  schedule: "0,30 17-23,0-14 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-count-daily-checks2-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - '/usr/local/bin/ruby bin/rails runner "Batch::CountDailyChecks.new.run(target_date: Date.yesterday)"'
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-delayed-checks
  labels:
    app: check-tool-delayed-checks
spec:
  schedule: "0 15 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-delayed-checks-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::DelayedChecks.new.run"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-counting-payments
  labels:
    app: check-tool-counting-payments
spec:
  schedule: "30 15 1 * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-counting-payments-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::CountingPayments.new.run"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-send-item-to-trouble-patrol
  labels:
    app: check-tool-send-item-to-trouble-patrol
spec:
  schedule: "0 14 * * 0"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-send-item-to-trouble-patrol-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::SendItemToTroublePatrol.new.run"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-reflesh-queue
  labels:
    app: check-tool-reflesh-queue
spec:
  schedule: "30 18 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-reflesh-queue-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - '/usr/local/bin/ruby bin/rails runner "Batch::RefleshQueue.new.run(queue_names: Util::CheckQueues.all.map(&:name))"'
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-tool-update-oldest-item-ids
  labels:
    app: check-tool-update-oldest-item-ids
spec:
  schedule: "0 19 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-tool-update-oldest-item-ids-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/ruby bin/rails runner "Batch::UpdateOldestItemIds.new.run"
              envFrom:
                - configMapRef:
                    name: check-tool-common-env
                - configMapRef:
                    name: check-tool-application-env
                - secretRef:
                    name: check-tool-secret
          restartPolicy: OnFailure
