bases:
  - ../../../../base/customer/pixta-editor
resources:
  - secret.yaml
  - ingress.yaml
  # - hpa.yaml
  - pdb.yaml
configMapGenerator:
  - name: editor-common-env
    behavior: merge
    literals:
      - S3_BUCKET=pixtavietnam-editor-production
      - RAILS_ENV=production
      - AWS_REGION=ap-northeast-1
      - DATABASE_USERNAME=admin
      - DATABASE_DBNAME=editor-production
      - DATABASE_HOST=editor-production.cyqbfzctkesh.ap-northeast-1.rds.amazonaws.com
      - DATABASE_HOST_SLAVE=editor-production.cyqbfzctkesh.ap-northeast-1.rds.amazonaws.com
  - name: editor-nginx-conf
    behavior: merge
    files:
      - configmap/editor-api.conf
  - name: editor-frontend-nginx-conf
    behavior: merge
    files:
      - configmap/editor.conf
  - name: editor-frontend-common-env
    literals:
      - NODE_ROOT=/usr/src/editor
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
  - deployment_patch.yaml
  - service_patch.yaml
  # - cronjob_patch.yaml
