apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pixta-uploader-sqs2s3-cronjob
  labels:
    app: pixta-uploader-sqs2s3-cronjob
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: true
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pixta-uploader-sqs2s3-cronjob
        spec:
          restartPolicy: Never
          volumes:
            - name: app
              persistentVolumeClaim:
                claimName: pixta-uploader-jp-pvc
          containers:
            - name: pixta-uploader-sqs2s3-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-uploader:latest
              volumeMounts:
                - mountPath: /srv/upload/
                  name: app
              command:
                [
                  "bash",
                  "-c",
                  "mkdir -p /srv/upload/complete/; /usr/local/bundle/bin/bundle exec /usr/local/bin/ruby /srv/www/pixta_uploader/script/sqs2s3.rb -e $DEPLOY_ENV",
                ]
              envFrom:
                - configMapRef:
                    name: pixta-uploader-application-env
                - secretRef:
                    name: pixta-uploader-secret
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pixta-uploader-clean-files-cronjob
  labels:
    app: pixta-uploader-clean-files-cronjob
spec:
  schedule: "*/45 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: true
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pixta-uploader-clean-files-cronjob
        spec:
          restartPolicy: Never
          volumes:
            - name: app
              persistentVolumeClaim:
                claimName: pixta-uploader-jp-pvc
          containers:
            - name: pixta-uploader-clean-files-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-uploader:latest
              volumeMounts:
                - mountPath: /srv/upload/
                  name: app
              command:
                [
                  "bash",
                  "-c",
                  "for type in jpg png eps zip jpeg; do find /srv/upload/ -iname '*.${type}' -ctime +10 -exec rm -rf {} +; done",
                ]
              envFrom:
                - configMapRef:
                    name: pixta-uploader-application-env
                - secretRef:
                    name: pixta-uploader-secret
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
