apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pngfm-pngcheck-cronjob
  labels:
    app: pngfm-pngcheck-cronjob
spec:
  schedule: "50 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pngfm-pngcheck-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: pngfm-pngcheck-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
              imagePullPolicy: Always
              command:
                [
                  "bash",
                  "-c",
                  "bin/rails runner 'Batch::RequestManagerBatch.new(PngItem::STATUS_NEW).run'",
                ]
              envFrom:
                - secretRef:
                    name: pngfm-secret
                - configMapRef:
                    name: pngfm-common-env
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pngfm-registag-cronjob
  labels:
    app: pngfm-registag-cronjob
spec:
  schedule: "50 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pngfm-registag-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: pngfm-registag-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
              imagePullPolicy: Always
              command:
                [
                  "bash",
                  "-c",
                  "bin/rails runner 'Batch::RequestManagerBatch.new(PngItem::STATUS_TRANSPARENT).run'",
                ]
              envFrom:
                - secretRef:
                    name: pngfm-secret
                - configMapRef:
                    name: pngfm-common-env
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pngfm-genoriginal-cronjob
  labels:
    app: pngfm-genoriginal-cronjob
spec:
  schedule: "50 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pngfm-genoriginal-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: pngfm-genoriginal-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
              imagePullPolicy: Always
              command:
                [
                  "bash",
                  "-c",
                  "bin/rails runner 'Batch::RequestManagerBatch.new(PngItem::STATUS_TAG).run'",
                ]
              envFrom:
                - secretRef:
                    name: pngfm-secret
                - configMapRef:
                    name: pngfm-common-env
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pngfm-exif-cronjob
  labels:
    app: pngfm-exif-cronjob
spec:
  schedule: "50 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pngfm-exif-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: pngfm-exif-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
              imagePullPolicy: Always
              command:
                [
                  "bash",
                  "-c",
                  "bin/rails runner 'Batch::RequestManagerBatch.new(PngItem::STATUS_ORIGINAL_JPG).run'",
                ]
              envFrom:
                - secretRef:
                    name: pngfm-secret
                - configMapRef:
                    name: pngfm-common-env
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pngfm-gencheck-cronjob
  labels:
    app: pngfm-gencheck-cronjob
spec:
  schedule: "50 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pngfm-gencheck-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: pngfm-gencheck-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
              imagePullPolicy: Always
              command:
                [
                  "bash",
                  "-c",
                  "bin/rails runner 'Batch::RequestManagerBatch.new(PngItem::STATUS_EXIF_DATA).run'",
                ]
              envFrom:
                - secretRef:
                    name: pngfm-secret
                - configMapRef:
                    name: pngfm-common-env
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pngfm-copy-cronjob
  labels:
    app: pngfm-copy-cronjob
spec:
  schedule: "10 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pngfm-copy-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: pngfm-copy-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
              imagePullPolicy: Always
              command:
                [
                  "bash",
                  "-c",
                  "bin/rails runner 'Batch::RequestManagerBatch.new(PngItem::STATUS_PNG_CHECK).run'",
                ]
              envFrom:
                - secretRef:
                    name: pngfm-secret
                - configMapRef:
                    name: pngfm-common-env
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pngfm-jpgcheck-cronjob
  labels:
    app: pngfm-jpgcheck-cronjob
spec:
  schedule: "20 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pngfm-jpgcheck-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: pngfm-jpgcheck-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
              imagePullPolicy: Always
              command:
                [
                  "bash",
                  "-c",
                  "bin/rails runner 'Batch::RequestManagerBatch.new(PngItem::STATUS_COPY).run'",
                ]
              envFrom:
                - secretRef:
                    name: pngfm-secret
                - configMapRef:
                    name: pngfm-common-env
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pngfm-checktool-cronjob
  labels:
    app: pngfm-checktool-cronjob
spec:
  schedule: "30 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pngfm-checktool-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: pngfm-checktool-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
              imagePullPolicy: Always
              command:
                [
                  "bash",
                  "-c",
                  "bin/rails runner 'Batch::RequestManagerBatch.new(PngItem::STATUS_JPG_CHECK).run'",
                ]
              envFrom:
                - secretRef:
                    name: pngfm-secret
                - configMapRef:
                    name: pngfm-common-env
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pngfm-product-cronjob
  labels:
    app: pngfm-product-cronjob
spec:
  schedule: "30 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pngfm-product-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: pngfm-product-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
              imagePullPolicy: Always
              command:
                [
                  "bash",
                  "-c",
                  "bin/rails runner 'Batch::RequestManagerBatch.new(PngItem::STATUS_REVIEWED_OK).run'",
                ]
              envFrom:
                - secretRef:
                    name: pngfm-secret
                - configMapRef:
                    name: pngfm-common-env
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pngfm-update-result-cronjob
  labels:
    app: pngfm-update-result-cronjob
spec:
  schedule: "40 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pngfm-update-result-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: pngfm-update-result-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
              imagePullPolicy: Always
              command:
                [
                  "bash",
                  "-c",
                  "bin/rails runner 'Batch::UpdateResultForPixtaMain.new.run'",
                ]
              envFrom:
                - secretRef:
                    name: pngfm-secret
                - configMapRef:
                    name: pngfm-common-env
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pngfm-abort-check-cronjob
  labels:
    app: pngfm-abort-check-cronjob
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pngfm-abort-check-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: pngfm-abort-check-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
              imagePullPolicy: Always
              command:
                [
                  "bash",
                  "-c",
                  "bin/rails runner 'Batch::RequestManagerBatch.new(PngItem::STATUS_PRE_ABORT).run'",
                ]
              envFrom:
                - secretRef:
                    name: pngfm-secret
                - configMapRef:
                    name: pngfm-common-env
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "700Mi"
