apiVersion: apps/v1
kind: Deployment
metadata:
  name: pngfm
  labels:
    app: pngfm
spec:
  selector:
    matchLabels:
      app: pngfm
  template:
    metadata:
      labels:
        app: pngfm
    spec:
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: pngfm-nginx-conf
          name: nginx-conf
        - configMap:
            items:
              - key: pixta-pngfm.conf
                path: pixta-pngfm.conf
            name: pngfm-nginx-conf
          name: site-conf
        - configMap:
            items:
              - key: puma.rb
                path: puma.rb
            name: pngfm-puma-rb
          name: puma-conf
        - name: web-sock
          emptyDir: {}
      containers:
        - name: pngfm-app
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/www/png-flow-manager/config/puma.rb
              name: puma-conf
              subPath: puma.rb
            - mountPath: /var/run/sock
              name: web-sock
          resources:
            requests:
              memory: "700Mi"
              cpu: "100m"
            limits:
              memory: "1400Mi"
          envFrom:
            - configMapRef:
                name: pngfm-common-env
            - secretRef:
                name: pngfm-secret
        - name: nginx
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:stable
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "200Mi"
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: /var/run/sock
              name: web-sock
            - mountPath: /config/pixta-pngfm.conf
              name: site-conf
              subPath: pixta-pngfm.conf
            - mountPath: /config/nginx.conf
              name: nginx-conf
              subPath: nginx.conf
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - cp -pf /config/nginx.conf /etc/nginx/nginx.conf && mkdir -p /etc/nginx/sites-enabled  && envsubst '$RAILS_ROOT' < /config/pixta-pngfm.conf > /etc/nginx/sites-enabled/pixta-pngfm.conf && nginx -s reload
            preStop:
              exec:
                command:
                  - /usr/sbin/nginx
                  - -s
                  - quit
          envFrom:
            - configMapRef:
                name: pngfm-common-env
