apiVersion: apps/v1
kind: Deployment
metadata:
  name: pngfm-checktool-result-poller
  labels:
    app: pngfm-checktool-result-poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pngfm-checktool-result-poller
  template:
    metadata:
      labels:
        app: pngfm-checktool-result-poller
    spec:
      nodeSelector:
        balance-spot-public-instance: "true"
      tolerations:
        - key: "balance-spot-public-instance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: pngfm-checktool-result-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
          imagePullPolicy: Always
          command:
            [
              "bash",
              "-c",
              "bin/rails runner 'Batch::ResponseBatches::GetChecktoolResult.new.run'",
            ]
          envFrom:
            - secretRef:
                name: pngfm-secret
            - configMapRef:
                name: pngfm-common-env
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pngfm-pngcheck-poller
  labels:
    app: pngfm-pngcheck-poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pngfm-pngcheck-poller
  template:
    metadata:
      labels:
        app: pngfm-pngcheck-poller
    spec:
      nodeSelector:
        balance-spot-public-instance: "true"
      tolerations:
        - key: "balance-spot-public-instance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: pngfm-pngcheck-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
          imagePullPolicy: Always
          command:
            [
              "bash",
              "-c",
              "bin/rails runner 'Batch::ResponseBatches::GetPngCheckResult.new.run'",
            ]
          envFrom:
            - secretRef:
                name: pngfm-secret
            - configMapRef:
                name: pngfm-common-env
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pngfm-jpgcheck-poller
  labels:
    app: pngfm-jpgcheck-poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pngfm-jpgcheck-poller
  template:
    metadata:
      labels:
        app: pngfm-jpgcheck-poller
    spec:
      nodeSelector:
        balance-spot-public-instance: "true"
      tolerations:
        - key: "balance-spot-public-instance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: pngfm-jpgcheck-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
          imagePullPolicy: Always
          command:
            [
              "bash",
              "-c",
              "bin/rails runner 'Batch::ResponseBatches::GetJpgCheckResult.new.run'",
            ]
          envFrom:
            - secretRef:
                name: pngfm-secret
            - configMapRef:
                name: pngfm-common-env
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pngfm-checktool-start-poller
  labels:
    app: pngfm-checktool-start-poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pngfm-checktool-start-poller
  template:
    metadata:
      labels:
        app: pngfm-checktool-start-poller
    spec:
      nodeSelector:
        balance-spot-public-instance: "true"
      tolerations:
        - key: "balance-spot-public-instance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: pngfm-checktool-start-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
          imagePullPolicy: Always
          command:
            [
              "bash",
              "-c",
              "bin/rails runner 'Batch::ResponseBatches::ChecktoolStartCheck.new.run'",
            ]
          envFrom:
            - secretRef:
                name: pngfm-secret
            - configMapRef:
                name: pngfm-common-env
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pngfm-product-poller
  labels:
    app: pngfm-product-poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pngfm-product-poller
  template:
    metadata:
      labels:
        app: pngfm-product-poller
    spec:
      nodeSelector:
        balance-spot-public-instance: "true"
      tolerations:
        - key: "balance-spot-public-instance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: pngfm-product-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:latest
          imagePullPolicy: Always
          command:
            [
              "bash",
              "-c",
              "bin/rails runner 'Batch::ResponseBatches::GetProductResult.new.run'",
            ]
          envFrom:
            - secretRef:
                name: pngfm-secret
            - configMapRef:
                name: pngfm-common-env
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pngfm-tag-poller
  labels:
    app: pngfm-tag-poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pngfm-tag-poller
  template:
    metadata:
      labels:
        app: pngfm-tag-poller
    spec:
      containers:
        - name: pngfm-tag-poller
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/png-flow-manager:stg-402192c
          imagePullPolicy: Always
          command:
            [
              "bash",
              "-c",
              "bin/rails runner 'Batch::ResponseBatches::GetTagResult.new.run'",
            ]
          envFrom:
            - secretRef:
                name: pngfm-secret
            - configMapRef:
                name: pngfm-common-env
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
