apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-png
  labels:
    app: worker-png
    stage: staging
spec:
  selector:
    matchLabels:
      app: worker-png
      stage: staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker-png
        stage: staging
