apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: pixta-downloader-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pixta-downloader
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        target:
          averageValue: 500m
          type: AverageValue
      type: Resource
