apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tag-suggestion-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tag-suggestion
  minReplicas: 0
  maxReplicas: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
