apiVersion: v1
kind: Secret
metadata:
    name: tag-suggestion-secret
stringData:
    ROLLBAR_ACCESS_TOKEN: ENC[AES256_GCM,data:Z4r2vUuPxf7wW+3rGHxJYdckH901hJRxtU21dOJ3xS4=,iv:+p6eJsMayIXz0/bWy9/my7vzenNL0Y5BmXfhJtq2S6w=,tag:928cHu5cS1GwLjyO6tR/xQ==,type:str]
    ENV: ENC[AES256_GCM,data:A0jQZYIewA==,iv:XYZ1XQwOQz8/fal8Osyjk4uP9lA/czYCnuEy/cs+8r4=,tag:8vbXVAectF+wGZia1m4dgQ==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:045675425505:key/ee38c497-6147-4bd3-a58a-ea8c9845be7c
          created_at: "2021-05-04T04:25:27Z"
          enc: AQICAHhobnnncr8XFXX4QKWeGumP2AjuF/t1WTZdjh0ZfApr6QGLqqWiBTzpupNChP8VOR9bAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZAMiboUOUptP+px3AgEQgDsrI6ioo2wAl7Rk2fR32OTfxZ+qAdmV8ChQN6bJXyWwf9ITnC17xN6+9q4w7v0FKtyQ9LFBGrVyhA872g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-04T04:25:28Z"
    mac: ENC[AES256_GCM,data:qekZ0aXc3eb0TglXu5LqKApbG7fevgdjXzfHqMTV4Kr4RZ2fE/Zc6MN7gItPtGo7s5HHYxwF2marQzzgAvVaj7e+B2Fp+zWj4ag5etiv70IyggxA9DDulJ0/S0jBw053IHqQ8Gvadmg0A6G98MMScsg8oQKkV0W2719RGiOYhpM=,iv:KYqrTHHKCMHXb3XslA7iW+NYyV9hk5hgRR+bU1tYtkA=,tag:VXt38S7EqEO2uSjyuG1fug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
