resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
# configMapGenerator:
#   - name: proximus-common-env
#     literals:
#       - NVIDIA_VISIBLE_DEVICES=0
#       - GPU_ID=0
# generatorOptions:
#   disableNameSuffixHash: true
