bases:
  - ../../../../base/lab/lab-pcc4f
resources:
  - scaledobject.yaml
configMapGenerator:
  - name: lab-pcc4f-conf
    files:
      - configmap/production.yaml
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
  - deployment_patch.yaml
