apiVersion: apps/v1
kind: Deployment
metadata:
  name: sendmail
  labels:
    app: sendmail
spec:
  selector:
    matchLabels:
      app: sendmail
  template:
    metadata:
      labels:
        app: sendmail
    spec:
      volumes:
        - emptyDir: {}
          name: app
        - configMap:
            name: sendmail-web-config
          name: web-conf
      containers:
        - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:stable
          name: sendmail-nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 30Mi
          volumeMounts:
            - mountPath: /app
              name: app
            - mountPath: /config
              name: web-conf
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health_check/database
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 30
            periodSeconds: 60
            successThreshold: 1
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /health_check/database
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 30
            successThreshold: 1
            periodSeconds: 60
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - rm -f /etc/nginx/conf.d/default.conf
                    && envsubst "$(env | awk -F = '{printf " $%s", $1}')" < /config/sendmail.conf > /etc/nginx/conf.d/sendmail.conf
                    && cp -pf /config/nginx.conf /etc/nginx/nginx.conf && nginx -s reload
            preStop:
              exec:
                command:
                  - /usr/sbin/nginx
                  - -s
                  - quit

        # Rails Application Container
        - name: sendmail-app
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/sendmail:latest
          imagePullPolicy: Always
          command:
            - sh
            - -c
          args:
            - cp -pR ${RAILS_ROOT}/public /app/public && bundle exec unicorn_rails -c /config/unicorn.rb
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: app
            - mountPath: /config
              name: web-conf
          resources:
            requests:
              memory: "400Mi"
              cpu: "75m"
            limits:
              memory: "800Mi"
              cpu: "150m"
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - postmap hash:/etc/postfix/sasl_passwd && postfix start
          envFrom:
            - configMapRef:
                name: sendmail-application-env
            - secretRef:
                name: sendmail-secret
