apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-assign-checks-cronjob
  labels:
    app: checktool-assign-checks-cronjob
    stage: production
spec:
  schedule: "40 * * * *"
  startingDeadlineSeconds: 180
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-assign-checks-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-assign-checks-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-counting-payment-cronjob
  labels:
    app: checktool-counting-payment-cronjob
    stage: production
spec:
  schedule: "30 0 1 * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-counting-payment-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-counting-payment-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-counting-queue-items-cronjob
  labels:
    app: checktool-counting-queue-items-cronjob
    stage: production
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-counting-queue-items-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-counting-queue-items-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:prod-0d02ddf
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-delayed-checks-cronjob
  labels:
    app: checktool-delayed-checks-cronjob
    stage: production
spec:
  schedule: "35 16 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-delayed-checks-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-delayed-checks-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-fix-checks-cronjob
  labels:
    app: checktool-fix-checks-cronjob
    stage: production
spec:
  schedule: "10,40 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-fix-checks-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-fix-checks-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:prod-0d02ddf
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-monthly-close-timesheet-cronjob
  labels:
    app: checktool-monthly-close-timesheet-cronjob
    stage: production
spec:
  schedule: "30 0 1 * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-monthly-close-timesheet-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-monthly-close-timesheet-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-reflesh-queue-cronjob
  labels:
    app: checktool-reflesh-queue-cronjob
    stage: production
spec:
  schedule: "30 19 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-reflesh-queue-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-reflesh-queue-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-remind-logtime-cronjob
  labels:
    app: checktool-remind-logtime-cronjob
    stage: production
spec:
  schedule: "0 14 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-remind-logtime-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-remind-logtime-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-send-check-result-cronjob
  labels:
    app: checktool-send-check-result-cronjob
    stage: production
spec:
  schedule: "20,50 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-send-check-result-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-send-check-result-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-send-item-to-trouble-patrol-cronjob
  labels:
    app: checktool-send-item-to-trouble-patrol-cronjob
    stage: production
spec:
  schedule: "10 22 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-send-item-to-trouble-patrol-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-send-item-to-trouble-patrol-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-send-labeled-highscore-items-cronjob
  labels:
    app: checktool-send-labeled-highscore-items-cronjob
    stage: production
spec:
  schedule: "15 23 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-send-labeled-highscore-items-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-send-labeled-highscore-items-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-start-check-items-cronjob
  labels:
    app: checktool-start-check-items-cronjob
    stage: production
spec:
  schedule: "25 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-start-check-items-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-start-check-items-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-summary-daily-checks-cronjob
  labels:
    app: checktool-summary-daily-checks-cronjob
    stage: production
spec:
  schedule: "25,55 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-summary-daily-checks-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-summary-daily-checks-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-summary-daily-checks-on-yesterday-cronjob
  labels:
    app: checktool-summary-daily-checks-on-yesterday-cronjob
    stage: production
spec:
  schedule: "35 1 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-summary-daily-checks-on-yesterday-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-summary-daily-checks-on-yesterday-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-timeout-checks-cronjob
  labels:
    app: checktool-timeout-checks-cronjob
    stage: production
spec:
  schedule: "15 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-timeout-checks-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-timeout-checks-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-update-oldest-items-cronjob
  labels:
    app: checktool-update-oldest-items-cronjob
    stage: production
spec:
  schedule: "25 20 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-update-oldest-items-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-update-oldest-items-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-update-ratio-footage-cronjob
  labels:
    app: checktool-update-ratio-footage-cronjob
    stage: production
spec:
  schedule: "5 20 * * 1-5"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-production
          labels:
            app: checktool-update-ratio-footage-cronjob
            stage: production
        spec:
          containers:
            - name: checktool-update-ratio-footage-job
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-check-tool:latest
---

