bases:
  - ../../../../base/item-flow/pixta-check-tool
resources:
  - ingress.yaml
  - secret.yaml
  - scaledobject.yaml
  - pdb.yaml
configMapGenerator:
  - name: check-tool-application-env
    behavior: merge
    literals:
      - RAILS_ENV=production
      - NODE_ENV=production
      - UNICORN_WORKER_PROCESSES='7'
      - UNICORN_TIMEOUT='300'
      - CACHE_STORE=pixta-cache-store.pixta.jp
  - name: check-tool-downloader-application-env
    behavior: merge
    literals:
      - RAILS_ENV=production
      - CACHE_STORE_LOCATION=contents.rddroc.0001.apne1.cache.amazonaws.com
      - ERROR_TRACKER_HOST=error-tracker.pixta.jp
      - NEWRELIC_APP_NAME=pixta-checktool-downloader
  - name: check-tool-nginx-env
    literals:
      - NGINX_HTTP_HOST="$http_host"
      - NGINX_VPN_RANGE="10.1.0.0/16"
      - NGINX_SERVER_NAME="check.pixta.jp"
  - name: check-tool-downloader-nginx-env
    literals:
      - NGINX_HTTP_HOST="$http_host"
      - NGINX_RESOLVER_HOST="10.1.0.2"
      # - NGINX_SERVER_NAME="sg-download-check-vn.pixta.jp pixta_downloader"
      - NGINX_SERVER_NAME="download-check-vn.pixta.jp sg-download-check-vn.pixta.jp download-check.pixta.jp euwest-download-check-vn.pixta.jp useast-download-check-vn.pixta.jp uswest-download-check-vn.pixta.jp sg-download-check.pixta.jp euwest-download-check.pixta.jp useast-download-check.pixta.jp uswest-download-check.pixta.jp uswest-download-check.pixta.jp"
generatorOptions:
  disableNameSuffixHash: false
patchesStrategicMerge:
  - deployment_patch.yaml
  - service_patch.yaml
  - polling_patch.yaml
  - cronjob_patch.yaml
  - delayed_job_patch.yaml
