apiVersion: v1
data:
    AIRBRAKE_PROJECT_ID: ENC[AES256_GCM,data:MLnN51VOnSY=,iv:kQK0S3zhzqRhZyPViNVeDSif/O9NVTRejLhz2kwHrzg=,tag:RFMv3hg97EBpQV+8wVwXMA==,type:str]
    AIRBRAKE_PROJECT_KEY: ENC[AES256_GCM,data:6vf41SlT/TqYMQoOsa2bBOnimD9DvyeYb7Qb/fLpm68M8ZHaINtAaoUPje0=,iv:y6KP7BDztQw4pcei/+5E7kBXbWRSmaPwXqCnUWt5nEY=,tag:6rOlvHQjFkV/DU5yzwmavg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:FInC3BJO6qo10Uz4KiSGU0NSDiePAWXpLBTFN5laqM2t8PqQFvsuNM2bLvSlM+DaP4TheeldeZTIWVxiYqQxUYjQEDJvz5AYGj6u46OQf4cpRMVT5YwBFhNhqgTqSXCI,iv:vuDR2H7BRHicXBJKpEoS+Sk9z9np3OW1ZXzAi0Bm/40=,tag:+coQtXRDJhE2GPlhjYWjCw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:uIrOCRUjUv5Sk7tTG2bGsA==,iv:4tpkHFunz0FNeKq20A3jjgPY50pUzqFAtZgHTyOaHj8=,tag:JRQf8msOQTDymjqQe2odjQ==,type:str]
    DB_PASS: ENC[AES256_GCM,data:U6zn5FqtGfjyXkxjw5b768r8mKbwu7h1xE1K8QXEtrQa9URS1TuCkHx+cMuFJZ1JFtiJ+THVoFSsqqMiibdD3Z/sdxA=,iv:KGv95/8YzyU0/SasgWq9U1GgMDYSX70SqL7ne1x2iSg=,tag:SofVzhvzGJeF1xO3Lq1Ukg==,type:str]
    DB_USER: ENC[AES256_GCM,data:BB0J3ADst4LUprO7+wO21Q==,iv:KzZJM/eeUZsxt9wtQ8u1RzdaK+P/QS44NZ/K+GNdM9I=,tag:CIWHEvRgD0YChRvptKpdDA==,type:str]
    DELAYED_JOB_PROCESS_NUM: ENC[AES256_GCM,data:XzrxbQ==,iv:ppSiGjYndCkhEtPSSIO+obrTZd4iuBQzrBCa+LG2u9k=,tag:fsA5ApoTdjbPgebrqFom3w==,type:str]
    ELASTICSEARCH_GRANTED_USER: ENC[AES256_GCM,data:0QJ9SBsA7uQHiLtlQAYEDA==,iv:+doXpC0ErlJRtPHDcExwtHfouyMNMaLW4l9FyhD6e0o=,tag:EWVl4HJ/Edb46YgGydbiBQ==,type:str]
    ELASTICSEARCH_HOST: ENC[AES256_GCM,data:izzdeVCWtAeGqpNYuLhTkCR1tXAlln2OcmU5KNGyF7TZhldBdcfNsC4BJFda9JyC5GN+GHSWdObx/LQprqatCWjRn3Tk+5MNCmaeqQLqo76MDTVhne7dprzNQ90=,iv:PQ+xQLLpkU7XRVEX219+EiYmuQU+HH1B8hkkxySKKAU=,tag:dJkk+LzzeNG77fXmemoy0Q==,type:str]
    ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:19MH0N8w3v+ISRLmmTLkCqNBLkxZpr4gsi3WgQ==,iv:7LYli9vOp/M0YEfqOuoDZH3K/AZHaSudZs8RlB+0ghA=,tag:T/hsoXVRJdlrbjFv7Fy6gg==,type:str]
    ELASTICSEARCH_PHOTO_INDEX: ENC[AES256_GCM,data:aQLGl7t4vl4Egdzpqsca/g==,iv:mNmFL+00v76Bv/5fK6yJr+7lJHCWhmhgvNe9U44MtIU=,tag:uALyI8be0n1gV+qqCsqNhQ==,type:str]
    ELASTICSEARCH_PHOTO_TYPE: ENC[AES256_GCM,data:Elu/oyhM0OsuVlJm,iv:iYaXn68s/+NXmdigcI5sXcACkpxW7eKRds4SaI5e39I=,tag:+VeqCPA9WhNWGEP/Kb+8rQ==,type:str]
    ELASTICSEARCH_PORT: ENC[AES256_GCM,data:kaI3F/Sa2MM=,iv:m+oS+NUpsiE+rTmIbOmnM7KuSkEXo6Sbr5CB+OuHO6c=,tag:8SiZZwA5sRXNNCThCV5oOw==,type:str]
    ELASTICSEARCH_SCHEME: ENC[AES256_GCM,data:ZwHoOQgfOEY=,iv:KhbkJYvTLWa1Ip+HZAaeHnOV0Y4oKkh6WXymzJ6dMIY=,tag:Ku709bG51Of+KkLzDUQEZg==,type:str]
    HOST_NAME: ENC[AES256_GCM,data:YK2qK9WF3kvyy/7IacObA8RAzIMVkxR/Mnywub3GvC0=,iv:e2w4TWQPnveXgQzccstJxP1Mohjb3vhXw1av639Ki4g=,tag:QHl8+VnTpCVabedQXfdxQw==,type:str]
    PIXTA_TOKEN: ENC[AES256_GCM,data:YwDZGaDt38knr58SAc5WigeqRTNNtsGwu+AtZfZUG99l0ISOfVJbdTgUbn7aBX4aaqtOOELiZsyAojuHT0cEgsRYidQcLER43jkRykEIVaSeB7f/v9TU1w==,iv:WpYxU+o277lU9T38k+lpsCRwHQuyoiMJxZ/98kOENqw=,tag:s0ElvWqX9ZsbnnwUkBs2VA==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:ekoQZi5XTdthRi7YeUPKNnrs10dk5REGVt4cfzZG28e7+Y9cUH7qU/jwJLsLzJIZYnhHfpH63WdxLzUgW3MRtk0WAOPG2T5v6y80xqwPkU9NxyhLD8/xeY6zuy7A+oRM9nsi7WaTHadNSRO8jJ2RHU4eMd75FlqMQJ74f2kA9he7n4IgI1VG/dm/sxf7h0x/1ro5hahDQkCIJiGQdYrj0qbmit6azXIwqL/bsQ==,iv:4OKlUztLoR9UUDQ05fxceV7pAH02TxcUJ0cm5lYWD88=,tag:w9F4TPYR+znaZUGkiLwLWQ==,type:str]
    SLACK_NOTIFICATION_CHANNEL: ENC[AES256_GCM,data:Eugw1hB8PZBrXHepYlX1hQ==,iv:JYxWYX45szl/5HANu/8t9CgfAu+MqArlXmCsek+AM9Y=,tag:vrnwU9039KkTqTRWiKsnBA==,type:str]
    SLACK_NOTIFICATION_URL: ENC[AES256_GCM,data:PAdA8vlXnja5qEulZdC8iCUKUgloKQ/o1Vx4ZpoxHJY2cho0g7XRVdn9mJSTXUJWSOb0enQ/SPfgWX7S1QBMRnWjE870g9A24VRSCd4HJyM5NtSHhkPnUVGe0Rd4trlYsABMR5QPY9I=,iv:zde7QV3UH1DN9CAvQBKdgzuy/LtO4bDvRZQk3ShzDNo=,tag:KkGwCIN+YZ0ZBJ5n61MMvw==,type:str]
kind: Secret
metadata:
    name: pngfm-secret
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:045675425505:key/97008896-549e-41e0-ac53-58069a992bec
          created_at: "2022-06-14T03:26:22Z"
          enc: AQICAHhuUCqBQXMCkUJlXaKih1U3DC5iUw0PEuanKcAmzvfX3gGqxC0I5St+7QhayEqnwy0QAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4tpNJ0XOJ1lG5Q1BAgEQgDtPDhfzG+pOACZ2OaZrtk77B2/LfbADH7SqoOm53R1xL3NZqCrwHBfUuoWizQEGqwY89FgyXGjwmCjq/Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-14T03:26:22Z"
    mac: ENC[AES256_GCM,data:XzshNtKOJsRPyVX/F5e85dvz5t00uINCf6pc3Vv1QDSBitAurilx+/xBRDjh2mxQhmERn3Srmq1tn6YQnDap8YNGaWDABYgVsKn8dp7mqMPVH8JtyqgrH9LC+Y3wxMTpRcLfJwRdMxNgPufzgZAk38BAAm7k+SLyJwSmkM423jk=,iv:BIEgy89keEa/BrObsDkHPz6bO/ftRfDBWxKV2HxWqgI=,tag:5+o85a8vZesqnV8KW+ImCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
