apiVersion: v1
kind: ConfigMap
metadata:
  name: pixta-common-env
data:
  ACTIVE_VISUAL_SIMILAR_IMAGE: "true"
  BIZTALK_BSID: topicimages
  CHATWORK_FOOTAGE_ON_DEMAND_ROOM_ID: "1.757507e+06"
  FOOTAGE_ON_DEMAND_ROOM_ID: ""
  ITEM_TAGS: production_item_tags
  MAUTIC_USER: admin
  RAILS_LOG_TO_STDOUT: "true"
  SANDBOX_ERROR_MAIL_ADDRESS: error+ruby2@pixta.co.jp
  SEARCHED_ITEMS: production_searched_items
  SMTP_HOST: smtp.sendgrid.net
  USE_CLOUD_SEARCH: "true"
