apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-pcc4f
  labels:
    app: lab-pcc4f
spec:
  selector:
    matchLabels:
      app: lab-pcc4f
  template:
    metadata:
      labels:
        app: lab-pcc4f
    spec:
      tolerations:
        - key: "spotInstance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      volumes:
        - name: pcc4f-data-vol
          persistentVolumeClaim:
            claimName: pcc4f-data-pvc-1
        - name: pcc4f-ckpts-vol
          persistentVolumeClaim:
            claimName: pcc4f-ckpts-pvc-1
      initContainers:
        - name: init-data
          image: xueshanf/awscli:latest
          command:
            [
              "/bin/sh",
              "-c",
              "aws s3 sync --delete s3://machine-learning-storage-stg/pcc4f/v3/ckpts/ /tmp/ckpts/",
            ]
          volumeMounts:
            - mountPath: /tmp/ckpts
              name: pcc4f-ckpts-vol
        - name: init-models
          image: xueshanf/awscli:latest
          command:
            [
              "/bin/sh",
              "-c",
              "aws s3 sync --delete s3://machine-learning-storage-stg/pcc4f/v3/data/ /tmp/data/",
            ]
          volumeMounts:
            - mountPath: /tmp/data
              name: pcc4f-data-vol
      containers:
        - name: lab-pcc4f
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/lab-pcc4f:v3.0.0
          imagePullPolicy: Always
          command:
            - "python3"
          args:
            - "main.py"
          resources:
            requests:
              memory: "1.2Gi"
              cpu: "785m"
            limits:
              memory: "2Gi"
              cpu: "1570m"
          volumeMounts:
            - name: pcc4f-data-vol
              mountPath: /pcc_v3/data/model_p.txt
              subPath: model_p.txt
            - name: pcc4f-ckpts-vol
              mountPath: /pcc_v3/src/trained_models/DeepSet_300_Parallel/DeepSet_300_Parallel.pth
              subPath: DeepSet_300_Parallel_final_footage.pth
