apiVersion: v1
kind: Secret
metadata:
    name: pixta-downloader-secret
stringData:
    DATABASE_PASSWORD: ENC[AES256_GCM,data:qc/dYo3vHJj7CSc81Y9bCQ==,iv:O/74NLYRlE8T6UY/pJQgG/epj+kLzkmebvL1U5jRS0Y=,tag:Od9yvblzru2T86m/WeSB4A==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:OyR2mAJMSQ==,iv:X3TMCEBdA7mgzL3DdsSbzqAzMRm8MPij0tE648rHcnk=,tag:R3EyN/Z3UOHLxfR1bhn7VQ==,type:str]
    HEALTH_CHECK_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:U8LrU3j1nuqdJS/jJ/UhoQ==,iv:oFMkva1Mwchfnv77iAfrIB3Q5aEEiRT/R5XJIO4YaOY=,tag:DSC893epAtc+Ntvfl8SFeQ==,type:str]
    HEALTH_CHECK_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:Vead3U6zj97CQmbjRJs=,iv:bXwVTfjuHO618e2li/F9VJXXQR8tH191QhNHYeI7GW4=,tag:7HnE2YRvrZrPOklGSDUDXg==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:tG/XxZuTuLytCqg76lru29KNGQVoY+m3NkM0Avc=,iv:IX3UZGqAHrGUzLN6u139W7+QPPjF+4UTnL7BSmaSZYw=,tag:SS/GY6UMzrOrVl1Dpvf0TA==,type:str]
    DATABASE_DBNAME: ENC[AES256_GCM,data:AFeABBAONBwxZzbtado=,iv:+bz5faczPpNTfJMNU0dPWUd6h94ENWRQqWpdPJ10gvk=,tag:PeQHzTTphN/FbXKp3ZO8cQ==,type:str]
    GITHUB_PACKAGES_READ_ACCESS_TOKEN: ENC[AES256_GCM,data:afaTmRELilmy9h+wVEbagDTW9Xks/rsjUW5w/seeVpOMHJSuCrQ0hA==,iv:QGNIVor7zk0OARmv2TGcQbP0Ic8pw7j2rRzOQHPwhUc=,tag:yinFRWdLO/puAg44TgjXjg==,type:str]
    ERROR_TRACKER_KEY: ENC[AES256_GCM,data:BdijD5JWmPUFQ732Zc/+smnEGcqfl0FmiKaR50ulREI=,iv:4xiO5ILuXBcNMDREz2lI8yEsnu/NCMi8Q0R9SpxKT3o=,tag:ChvcN9Nh+NIkLnnFyNCUZQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:h/PdLUFMu1Jic2iFYj5yK9MZEzPJTpsv6hb+vWXROazCPWFGKfd5aBJ6bkmxrLXWJBnmTtkZjwFM8Lya2biiDik0eBq07qyUeJcuJ6Bu6dOKmpDmCIW60zfTGlYeb1mXjm4jrcHPcJSBBt7GkbZOSW/ZOKHKscuD20FVfNsJ/PE=,iv:/5rN/GIRKjMax5B/NxkYZlkFcz2Pdtdv6SB8s4Xe1l4=,tag:tcFKR2suI7C2thr3kyI0yQ==,type:str]
    ROLLBAR_ACCESS_TOKEN: ENC[AES256_GCM,data:lDHbWFyOKqCBLt1JiMEvWgEdnMCDSQcGqwtb6sK8t3g=,iv:NfFMkPWztPduOiNZZYoKg1OElvI1AyCr7/mtocDjkpk=,tag:8ZxuDwZdKgmm231M0iywVg==,type:str]
    DD_ENV: ENC[AES256_GCM,data:FrtHCB4dDsYp+A==,iv:R26DR2HKXqgv0nxkOOGDRYGiXouoelI0wBVlFUSz4vc=,tag:EsPJ0OXkXTBqWQMhM/DulA==,type:str]
    DD_SERVICE: ENC[AES256_GCM,data:jPpgIWpzXpELJxjFGYKU4w==,iv:FLA5mQDZC50hI5ilkJq/VU5pkrhGn9R3cJFMohRm7Ko=,tag:DKpBwOwis6epQGl2W0tJCQ==,type:str]
    DD_VERSION: ENC[AES256_GCM,data:AvmR5pkh,iv:i0SMdUYiPFCSSY8NhZLgWulcLh74ADrqC2uwQRqMA2o=,tag:oWeRoLp4UGy7mcWfSTjrQw==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:045675425505:key/97008896-549e-41e0-ac53-58069a992bec
          created_at: "2022-01-24T07:52:27Z"
          enc: AQICAHhuUCqBQXMCkUJlXaKih1U3DC5iUw0PEuanKcAmzvfX3gFtUqWWLnEhtQLjMBo4HnKpAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvw0Fgmxj+Yir1BSwAgEQgDvVXFYyjIf7S1ccwYTl31HqlWT2fTYWDoDup95RWnnN36nHDXhI550oNAdFjll0BVinYpnIANcUKpHGZw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-24T07:52:28Z"
    mac: ENC[AES256_GCM,data:/gYOWaiQiSvujujINHt76G0w9n5CsRf7Ya8KCgLwxO/DDX48rV0ygHGH56s5EEVC7gA49Dy70J06KHfeIwPq21L57hxG9XWk2kypA3dOp+K9FnmF4x+dBdRnndDn0TaPEXLRG0RPUUNFo7WlwoDOR9ZgDStaOywWwKnme7vNqDM=,iv:rmkNDc9Gcnnp0aUjLvMgSz4y7J25P9wXgOFhCuA2B7c=,tag:iyFRIgrGT7e7xqGVQb6/PQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
