apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pixta-job-ltr-model-pipeline
  labels:
    app: pixta-job-ltr-model-pipeline
    stage: staging
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: pixta-job-ltr-model-pipeline
            stage: staging
        spec:
          nodeSelector:
            node.kubernetes.io/lifecycle: spot
            lab-worker: "true"
          restartPolicy: Never
          containers:
            - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/lab-ltrv2-model-pipeline:v1.1.5
              name: job-ltr-model-pipeline
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 4
  suspend: false
