---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.image-highscore: regex:^stg.*
    fluxcd.io/tag.init-ckpts: glob:alpine-3.11
  name: image-highscore
  namespace: stg-lab
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: image-highscore
      $setElementOrder/initContainers:
      - name: init-ckpts
      - name: init-ckpt
      - name: init-tagemb
      containers:
      - image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/lab-highscore-image:stg-e8e89f2
        name: image-highscore
      initContainers:
      - image: xueshanf/awscli:alpine-3.11
        name: init-ckpts
      - image: public.ecr.aws/bitnami/aws-cli:1.27.2-debian-11-r0
        name: init-ckpt
      - image: public.ecr.aws/bitnami/aws-cli:1.27.2-debian-11-r0
        name: init-tagemb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.jic: semver:~2
    fluxcd.io/tag.nginx: glob:stable
  name: jic
  namespace: stg-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.init-ckpts: glob:alpine-3.11
    fluxcd.io/tag.lab-facesearch: semver:~3
  name: lab-facesearch
  namespace: stg-lab
spec:
  template:
    spec:
      $setElementOrder/initContainers:
      - name: init-ckpts
      initContainers:
      - image: xueshanf/awscli:alpine-3.11
        name: init-ckpts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.init-data: glob:alpine-3.11
    fluxcd.io/tag.init-models: glob:alpine-3.11
    fluxcd.io/tag.lab-pcc: semver:~3
  name: lab-pcc
  namespace: stg-lab
spec:
  template:
    spec:
      $setElementOrder/initContainers:
      - name: init-data
      - name: init-models
      initContainers:
      - image: xueshanf/awscli:alpine-3.11
        name: init-data
      - image: xueshanf/awscli:alpine-3.11
        name: init-models
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.init-data: glob:alpine-3.11
    fluxcd.io/tag.init-models: glob:alpine-3.11
    fluxcd.io/tag.lab-pcc4f: semver:~3
  name: lab-pcc4f
  namespace: stg-lab
spec:
  template:
    spec:
      $setElementOrder/initContainers:
      - name: init-data
      - name: init-models
      initContainers:
      - image: xueshanf/awscli:alpine-3.11
        name: init-data
      - image: xueshanf/awscli:alpine-3.11
        name: init-models
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.nginx: glob:stable
    fluxcd.io/tag.tag-suggestion: semver:~2
  name: tag-suggestion
  namespace: stg-lab
spec:
  template:
    spec:
      $setElementOrder/initContainers:
      - name: init-ckpt
      - name: init-classes
      initContainers:
      - image: xueshanf/awscli:alpine-3.11
        name: init-ckpt
      - image: xueshanf/awscli:alpine-3.11
        name: init-classes
