# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *.dev.yaml,
        # KMS set A is used
        - path_regex: ./*
          kms: 'arn:aws:kms:ap-southeast-1:250506505253:key/592be777-d25f-49cb-963a-d241ed24f558'
          encrypted_regex: ^(data|stringData)$
        - path_regex: ./*
          kms: 'arn:aws:kms:ap-southeast-1:250506505253:key/592be777-d25f-49cb-963a-d241ed24f558'
          encrypted_regex: ^(data|stringData)$