# creation rules are evaluated sequentially, the first match wins
creation_rules:
    - kms: 'arn:aws:kms:ap-northeast-1:045675425505:key/97008896-549e-41e0-ac53-58069a992bec'
      encrypted_regex: ^(data|stringData)$