apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: example
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: Dev/Nginx/test
      versionId: edbd8170-cf66-4c91-abc7-15a454ebc93c