bases:
  - ../../../../base/customer/sendmail
resources:
  - ingress.yaml
  - secret.yaml
  # - scaledobject.yaml
configMapGenerator:
  - name: sendmail-application-env
    behavior: merge
    literals:
      - RAILS_ENV=staging
      - DATABASE_HOST=sendmail-staging.cyqbfzctkesh.ap-northeast-1.rds.amazonaws.com
      - DATABASE_DBNAME=sendmail_production
      - UNICORN_TIMEOUT=600
  - name: sendmail-nginx-env
    literals:
      - NGINX_HTTP_HOST="$http_host"
      - NGINX_SERVER_NAME="sendmail-staging.pixtastock.com"
  - name: sendmail-web-config
    behavior: merge
    files:
      - configmap/sendmail.conf
  - name: sendmail-mail-config
    files:
      - configmap/main.cf
generatorOptions:
  disableNameSuffixHash: false
patchesStrategicMerge:
  - deployment_patch.yaml
  - service_patch.yaml
