apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixta-mass-mailer
  labels:
    app: pixta-mass-mailer
spec:
  selector:
    matchLabels:
      app: pixta-mass-mailer
  template:
    metadata:
      labels:
        app: pixta-mass-mailer
    spec:
      volumes:
        - emptyDir: {}
          name: app
        - configMap:
            name: pixta-mass-mailer-web-config
          name: web-conf
      containers:
        - image: nginx:stable
          name: pixta-mass-mailer-nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 30Mi
          volumeMounts:
            - mountPath: /app
              name: app
            - mountPath: /config
              name: web-conf
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - rm -f /etc/nginx/conf.d/default.conf
                    && envsubst "$(env | awk -F = '{printf " $%s", $1}')" < /config/pixta-mass-mailer.conf > /etc/nginx/conf.d/pixta-mass-mailer.conf
                    && cp -pf /config/nginx.conf /etc/nginx/nginx.conf && nginx -s reload
            preStop:
              exec:
                command:
                  - /usr/sbin/nginx
                  - -s
                  - quit

        # Rails Application Container
        - name: pixta-mass-mailer-app
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-mass-mailer:latest
          imagePullPolicy: Always
          command:
            - sh
            - -c
          args:
            - cp -pR ${RAILS_ROOT}/public /app/public && bundle exec unicorn_rails -c /config/unicorn.rb
          volumeMounts:
            - mountPath: /app
              name: app
            - mountPath: /config
              name: web-conf
          resources:
            requests:
              memory: "400Mi"
              cpu: "75m"
            limits:
              memory: "800Mi"
              cpu: "150m"
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - postmap hash:/etc/postfix/sasl_passwd && postfix start
          envFrom:
            - configMapRef:
                name: pixta-mass-mailer-application-env
            - secretRef:
                name: pixta-mass-mailer-secret
