resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: pixta-mass-mailer-application-env
    literals:
      - RAILS_ROOT=/pixta-mass-mailer
      - RAILS_LOG_TO_STDOUT=true
      - NEWRELIC_PRO=false
      - AWS_REGION=ap-northeast-1
      - POSTGRES_HOST_AUTH_METHOD=trust
  - name: pixta-mass-mailer-web-config
    files:
      - configmap/nginx.conf
      - configmap/unicorn.rb
generatorOptions:
  disableNameSuffixHash: false
