apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: footage-resize-scaledobject
spec:
  scaleTargetRef:
    name: footage-resize
  # how frequently in seconds does KEDA poll Prometheus
  # pollingInterval: 15 # Optional. Default: 30 seconds
  # cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 0 # Optional. Default: 0
  maxReplicaCount: 27 # Optional. Default: 100
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-trigger-auth-aws-role
      metadata:
        queueURL: https://sqs.ap-northeast-1.amazonaws.com/045675425505/footage_resize_request_jp_production
        queueLength: "8"
        # Required: awsRegion
        awsRegion: "ap-northeast-1"
        identityOwner: pod # Optional. Default: pod
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: footage-resize-on-submit-scaledobject
spec:
  scaleTargetRef:
    name: footage-resize-on-submit
  # how frequently in seconds does KEDA poll Prometheus
  # pollingInterval: 15 # Optional. Default: 30 seconds
  # cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 1 # Optional. Default: 0
  maxReplicaCount: 27 # Optional. Default: 100
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-trigger-auth-aws-role
      metadata:
        queueURL: https://sqs.ap-northeast-1.amazonaws.com/045675425505/footage_on_submit_request_jp_production
        queueLength: "8"
        # Required: awsRegion
        awsRegion: "ap-northeast-1"
        identityOwner: pod # Optional. Default: pod
