apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-assign-checks-cronjob
  labels:
    app: checktool-assign-checks-cronjob
    stage: staging
spec:
  suspend: true
  schedule: "40 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-assign-checks-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-assign-checks-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-counting-payment-cronjob
  labels:
    app: checktool-counting-payment-cronjob
    stage: staging
spec:
  schedule: "30 0 1 * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-counting-payment-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-counting-payment-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-counting-queue-items-cronjob
  labels:
    app: checktool-counting-queue-items-cronjob
    stage: staging
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-counting-queue-items-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-counting-queue-items-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-delayed-checks-cronjob
  labels:
    app: checktool-delayed-checks-cronjob
    stage: staging
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-delayed-checks-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-delayed-checks-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-fix-checks-cronjob
  labels:
    app: checktool-fix-checks-cronjob
    stage: staging
spec:
  schedule: "10,40 * * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-fix-checks-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-fix-checks-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-monthly-close-timesheet-cronjob
  labels:
    app: checktool-monthly-close-timesheet-cronjob
    stage: staging
spec:
  schedule: "0 4 1 * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-monthly-close-timesheet-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-monthly-close-timesheet-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-reflesh-queue-cronjob
  labels:
    app: checktool-reflesh-queue-cronjob
    stage: staging
spec:
  schedule: "30 22 * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-reflesh-queue-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-reflesh-queue-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-remind-logtime-cronjob
  labels:
    app: checktool-remind-logtime-cronjob
    stage: staging
spec:
  schedule: "0 16 * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-remind-logtime-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-remind-logtime-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-send-check-result-cronjob
  labels:
    app: checktool-send-check-result-cronjob
    stage: staging
spec:
  schedule: "20,50 * * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-send-check-result-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-send-check-result-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-send-item-to-trouble-patrol-cronjob
  labels:
    app: checktool-send-item-to-trouble-patrol-cronjob
    stage: staging
spec:
  schedule: "10 22 * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-send-item-to-trouble-patrol-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-send-item-to-trouble-patrol-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-send-labeled-highscore-items-cronjob
  labels:
    app: checktool-send-labeled-highscore-items-cronjob
    stage: staging
spec:
  schedule: "15 23 * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-send-labeled-highscore-items-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-send-labeled-highscore-items-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-start-check-items-cronjob
  labels:
    app: checktool-start-check-items-cronjob
    stage: staging
spec:
  schedule: "25 * * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-start-check-items-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-start-check-items-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-summary-daily-checks-cronjob
  labels:
    app: checktool-summary-daily-checks-cronjob
    stage: staging
spec:
  schedule: "25,55 * * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-summary-daily-checks-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-summary-daily-checks-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-summary-daily-checks-on-yesterday-cronjob
  labels:
    app: checktool-summary-daily-checks-on-yesterday-cronjob
    stage: staging
spec:
  schedule: "35 1 * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-summary-daily-checks-on-yesterday-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-summary-daily-checks-on-yesterday-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-timeout-checks-cronjob
  labels:
    app: checktool-timeout-checks-cronjob
    stage: staging
spec:
  schedule: "15 * * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-timeout-checks-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-timeout-checks-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-update-oldest-items-cronjob
  labels:
    app: checktool-update-oldest-items-cronjob
    stage: staging
spec:
  schedule: "0 4 * * *"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-update-oldest-items-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-update-oldest-items-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checktool-update-ratio-footage-cronjob
  labels:
    app: checktool-update-ratio-footage-cronjob
    stage: staging
spec:
  schedule: "5 20 * * 1-5"
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
          labels:
            app: checktool-update-ratio-footage-cronjob
            stage: staging
        spec:
          containers:
            - name: checktool-update-ratio-footage-cronjob
              image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/pixta-checktool-job:stg-latest
---
