apiVersion: v1
kind: Secret
metadata:
    name: check-tool-downloader-secret
stringData:
    DATABASE_PASSWORD: ENC[AES256_GCM,data:lOj36eJ5SPtF,iv:yZBYRLOXgNFbaJYSIvulUXBtMVcufaCPwvEEI7MLtFA=,tag:AcOPu551CsuyQ5ZePlxs7w==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:vLIymYksxA==,iv:/BxdrSfwK/19+bNvKw1v6QEDlbn9xcUtoXoYOD+efcI=,tag:TdUAl6uNk48ppPUKH2FVsQ==,type:str]
    DATADOG_NAME: ENC[AES256_GCM,data:ly4b5KxMh8RKVcemk9hDQJUIK1E=,iv:ffpvy0WzvXLovJUUQIJYi3iRfR9xf4ShLdPlzSOVpLA=,tag:QB5p4dBxTiQwOoqUFH9RHw==,type:str]
    DD_ENV: ENC[AES256_GCM,data:WI35PrvIYQ==,iv:+wMLW+vXVZSztmty3jKLFVWrnHgoTVUE7pzCqRo64r0=,tag:Qn9/I5DjXPe72hZlp0oj4Q==,type:str]
    DD_SERVICE: ENC[AES256_GCM,data:AO50Ww5c5ATm6J2yA98FWjQV3Sg=,iv:I99e+vBsbOJe2HwOO2ej7M8pLoATaTnUsjOR4p85AVw=,tag:N10Vji8qmH6DZ1Ps6DuwdA==,type:str]
    DD_VERSION: ENC[AES256_GCM,data:6lm7o6CV,iv:5thNdR0b1wfNcMm/Cc9qa5uMMH48VR95xQ3b/hQsov4=,tag:2abjh/FbzuLX2Q/YaRamkg==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:045675425505:key/ee38c497-6147-4bd3-a58a-ea8c9845be7c
          created_at: "2022-10-11T03:37:26Z"
          enc: AQICAHhobnnncr8XFXX4QKWeGumP2AjuF/t1WTZdjh0ZfApr6QFWZ9q5IxGRzAfbGj8MDT3AAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBqbAGXFwb6zVN18VAgEQgDupM89NvakM564c7ywe1egbdj8y6UmUula3Np5x8+I0RkUrV2bBm40Rq0/mrP7nbDc7J3vgNvIg+y1AYg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-11T03:37:27Z"
    mac: ENC[AES256_GCM,data:134Ynd2t2/jKst0yz22JMlS7rdxxrdP732yxWqt5guNLzraQEk9GbNMIsenMvlsrAoI5vlJjXbbP/Ie6VzKANjtvC6q+JZLOS0y02TUuaJyboFZRy+cKUg/vi2mA8xkJ7+SoRj2d1hZqeCuct5UeZ1OkPROH1wX3SMPlCeyopjk=,iv:RkNflrtMZNRXl13GDnnAv6Ps7RQsu6IcexmGWLDM3vU=,tag:spJSDsRY6AQOAjHX9zJ5bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
stringData:
    PIXTA_MAIN_AUTH_TOKEN: ENC[AES256_GCM,data:cJGWztSv4bo8OfEA/0hZfPk0ftkBYasyaYLHQ/h6GuyDa540JnIyrGqeK4pY+2PDUBLoUgUum0/o6orEDTZWWA==,iv:0A1NEbO5kbe4TMmNdBLSF7nCmbYb51Imb27wAsGt0wg=,tag:KigpdmGTKxkjgHLWd7R2bw==,type:str]
    PIXTA_API_SECRET: ENC[AES256_GCM,data:CAd5VK3UB50+J8L1Mnm3AfXaXHWvL2tqMYcNX/bckrVNSaQs/45FM17lptXYjDroxmhMl56yfjdJNJUNBLS99A==,iv:oGRCSvN+8Cx+0euKK5lxMv3aDfb1Ocf7LpK75H29U7U=,tag:TLlwi/ap/HXny0GRPPCizQ==,type:str]
    PIXTA_API_ID: ENC[AES256_GCM,data:figRg15P2lSITTPoqM+R/70U5RDIjFdjb35zH35X5kREX+4STgKqrNIe8Mw51NbSuT1mDTVuerMMDg7dI8nOTw==,iv:tLngRCXI/gOxhRCTlGfKiJ68YdXzAnIs0X4Ejmg0qhg=,tag:1BvNqZPsESZIUY98ZfD1Ig==,type:str]
    ERROR_TRACKER_ID: ENC[AES256_GCM,data:ebSKoEPj,iv:cOfiszfAamZSCWKzeow/81iouLYCKBNmTIzs7Nv2neE=,tag:VaWAmggGcRpMFBU2Kx22mQ==,type:str]
    ERROR_TRACKER_KEY: ENC[AES256_GCM,data:Vvsm2vAQF/xAn1FS7sZNHK72UCeK28dkr3ga3buWa/A=,iv:EgQ3oZkbyeXFoJvqt6oPYYRB/txGZCqKJcMnAMVWmVY=,tag:LPeI3T6EVW1CfzkC9KwUqg==,type:str]
    CACHE_STORE: ENC[AES256_GCM,data:Dbx1mJutSDYfII+etALRVT0MMpPWYaND/Hg=,iv:PV7a7vV/LUlfDk7zB5fUZAnxvPrQrznfs3/QY8l8C0U=,tag:AEw+6X5ZfupXJHLzxdL8Cw==,type:str]
    RDS_RESTORE_ACCESS_KEY: ENC[AES256_GCM,data:K6U1o902cizWzktWVgHQ2RuxdcI=,iv:p+uJQGR8KPEGkfVSKeFV0pHDzMH8QUhZ3TW1Xtwy+Kk=,tag:HX8ET5y5hyxwWTJeydD6tg==,type:str]
    RDS_RESTORE_SECRET_KEY: ENC[AES256_GCM,data:VjX+0rmGKTnF5m5lYyEiitsnyB9OuCIMhibKl/Y/fx0P9KdMgXMgmA==,iv:V0v/3JneWWI07pRf4iq2V2h/oR4WoKkzRRa8UdglgYk=,tag:pxiUPTaC2OAR/7rDUideIQ==,type:str]
    RDS_ENDPOINT: ENC[AES256_GCM,data:01E1IzAF+/KqiQeaBKdyp1cUf6AnPh0Lh86CX3uN205ytfficeZLA/xITvBt,iv:UM5wH+c+RCHzAE1irpOTNlTX1NVEJstb7q6DGqeRxPw=,tag:/pM5/utuiFv1n6svAZ6ITg==,type:str]
    RDS_RERSOURCE_NAME: ENC[AES256_GCM,data:vdnvbOQg25zHeGbUskPBNxgyu+R6EOdkl/cj//8E8WtoT0Pd5qIBHZ6a,iv:Nem+NCzUcywy5FghbrK6AmbNNyV/dW0fxyQwwvi56vA=,tag:Zsk2O/DeUftMMVbytpR9QQ==,type:str]
    ROLLBAR_ACCESS_TOKEN: ENC[AES256_GCM,data:5nC3eVLn2vZjFFEQQ8Dl3UEw5EUp/t60bHnUhLqvzRY=,iv:/9krUGBRvwWMefoorswfXTv0M2jvv6enLoDbWdTAhc0=,tag:YVIbjC+yKX5/kYQnwsz16Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Wwlgi/Om8g6EhM8QPWPfNLgQ2Lk=,iv:6hgKeEQBUok5aJbBT990KOUCuKPN22rf0dQfee6ghrc=,tag:bsCbykuo1zUtxL31u4z8SA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/d4xeQ3N6BZuH58xi2doJPlETynrHJ+SvwG8RuUNYrVHrocIp7AnFQ==,iv:dqSXOSsuKT6ec+uhhLs5wS0uKzXWI8HAtaxKfMRrO3I=,tag:C5TdXpc8eeNQd3viVwS+gw==,type:str]
    DATABASE_DBNAME: ENC[AES256_GCM,data:MNDl0CfgGdWQ,iv:yz4aMbcRSIhDytn7pPQ5NiTPMdruf53/0Kn9om1wh2Q=,tag:aABeU53/Wb/3u4j2A8U2ag==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:sg4aiiQ=,iv:qg+oEGSPt6LI28Fu0lvT9mBvTiv6HW592vvRcUwWoM8=,tag:3061ju+K9tTDbxjNNUXKjw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:grRbbYouTYGYS/BUMOfIPw==,iv:L/7/Kr8f1dTBC1yYnoxKIDT/j3thSwwLdUceWndgTfs=,tag:ChgcBAYhVqbMLJkkH+leaA==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:cNOlZyboNpaOAOUk3ICSe5wTITevk5w3+eC83su14eZ4fbSX7ceffJw/EvJpvFP5bhF3Xrn42RO8AjSDdW/ZcmZL,iv:14kGo2k9+nJTuIN6TQ3oFSjLQVAVq2L9ADt0rSRCPK4=,tag:e+nLAdg5QpigrrzDHAEX5g==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:jKs1YXJzDUb/Jxs2U4Wf929zJhNQad8O4sCMHZ0GEuct7xZwTSQtPn1Ryf9RqQSCPLWxFU+7,iv:Rs8il5PWmHNSl4ec4HiGvJrPMl5wC/k2ZEVInAd8MO0=,tag:gQYoVQpOhHNsgU1uXFXdBg==,type:str]
kind: Secret
metadata:
    name: check-tool-secret
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:045675425505:key/ee38c497-6147-4bd3-a58a-ea8c9845be7c
          created_at: "2022-10-11T03:37:26Z"
          enc: AQICAHhobnnncr8XFXX4QKWeGumP2AjuF/t1WTZdjh0ZfApr6QFWZ9q5IxGRzAfbGj8MDT3AAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBqbAGXFwb6zVN18VAgEQgDupM89NvakM564c7ywe1egbdj8y6UmUula3Np5x8+I0RkUrV2bBm40Rq0/mrP7nbDc7J3vgNvIg+y1AYg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-11T03:37:27Z"
    mac: ENC[AES256_GCM,data:134Ynd2t2/jKst0yz22JMlS7rdxxrdP732yxWqt5guNLzraQEk9GbNMIsenMvlsrAoI5vlJjXbbP/Ie6VzKANjtvC6q+JZLOS0y02TUuaJyboFZRy+cKUg/vi2mA8xkJ7+SoRj2d1hZqeCuct5UeZ1OkPROH1wX3SMPlCeyopjk=,iv:RkNflrtMZNRXl13GDnnAv6Ps7RQsu6IcexmGWLDM3vU=,tag:spJSDsRY6AQOAjHX9zJ5bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restore-db-snapshot-secret
stringData:
    credentials: ENC[AES256_GCM,data:MsDl+Ypue9akDxFHvqltGv3HfFW7jciIxR+giR9N8Vim1sFogVMOITbXZgELv9wokYgyGyrKu3Y82o8SaJR9kginDky2a5JxeCCMV8d5K/QWxpkJswDOXryx4piFX6DICjVx7gamyS+UVuTBTgbKumyvUSd/ia3BXobkFcdiWMX72tv24zvuV7frCp5WGmxn1JA2AT7sIQgNQvKtxwH2F4GWI5hPe4G9V5CQzh1cMURr2JldGach6aAkRKFpPIgHJ6T+nxnkPhA4oqR9rlWX0FUs17qM9n8JqZnSd8tB1lueirQ8bxxlZN5WJ01ccz4HdyP17655,iv:rWKtXVqJmdaAZ7SAtePY/sR89hyhuC/e5jpwp2Ur1pY=,tag:9upOyBPpyH0gpPfVlla/zw==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:045675425505:key/ee38c497-6147-4bd3-a58a-ea8c9845be7c
          created_at: "2022-10-11T03:37:26Z"
          enc: AQICAHhobnnncr8XFXX4QKWeGumP2AjuF/t1WTZdjh0ZfApr6QFWZ9q5IxGRzAfbGj8MDT3AAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBqbAGXFwb6zVN18VAgEQgDupM89NvakM564c7ywe1egbdj8y6UmUula3Np5x8+I0RkUrV2bBm40Rq0/mrP7nbDc7J3vgNvIg+y1AYg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-11T03:37:27Z"
    mac: ENC[AES256_GCM,data:134Ynd2t2/jKst0yz22JMlS7rdxxrdP732yxWqt5guNLzraQEk9GbNMIsenMvlsrAoI5vlJjXbbP/Ie6VzKANjtvC6q+JZLOS0y02TUuaJyboFZRy+cKUg/vi2mA8xkJ7+SoRj2d1hZqeCuct5UeZ1OkPROH1wX3SMPlCeyopjk=,iv:RkNflrtMZNRXl13GDnnAv6Ps7RQsu6IcexmGWLDM3vU=,tag:spJSDsRY6AQOAjHX9zJ5bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
