apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfm
  labels:
    app: pfm
    stage: staging
spec:
  selector:
    matchLabels:
      app: pfm
      stage: staging
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
      labels:
        app: pfm
        stage: staging
