apiVersion: v1
kind: Secret
metadata:
    name: worker-png-to-jpg-secret
stringData:
    AIRBRAKE_API_KEY: ENC[AES256_GCM,data:XVt7tCKOok+F3AbtAsqjE0qt2VMbwQ6TuRMlJxbzl+8=,iv:cB61rwz20l6a5rxaQ0JDKnodIcI4CGWMmvJ66ckUrfM=,tag:/kKv843P3UzMIX40WC3u/Q==,type:str]
type: Opaque
sops:
    kms:
    -   arn: arn:aws:kms:ap-northeast-1:045675425505:key/ee38c497-6147-4bd3-a58a-ea8c9845be7c
        created_at: '2020-09-29T09:30:16Z'
        enc: AQICAHhobnnncr8XFXX4QKWeGumP2AjuF/t1WTZdjh0ZfApr6QGH8zLy3tm5GUx6zDWRLHeyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMd+fg2NvEVdAeMTi/AgEQgDs3Gx+RjTTozTMmNvHnfRfjTlPEswUxLyYQ1oe/A0HP6K6HZxye9JaHV7k+fOKFTx5XM/XHv89X/TzD9A==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-29T09:30:17Z'
    mac: ENC[AES256_GCM,data:o99+3yePJPFftnKE2IvuSi6mM5pZ+5sZkJOLOswzQbZmbYJl4ldDsSUTA2icIky1fJkokdgSXRkUw66FmSucs7JBbMZL+btZI68umSApkFbk6jvGoDVqWSHwftPKvKCV8n7KvmThZ1SIf1YPqTGZK8OLbQNyCQVgmKdFZy31KlU=,iv:5iz9CBQ0X8oGVdg153XOoSCnT+59gKSUNNhTR1pgGDI=,tag:mmXvI0rImcxlMaI0B2TmIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.0
