apiVersion: apps/v1
kind: Deployment
metadata:
  name: epsfm
  labels:
    app: epsfm
    stage: staging
spec:
  selector:
    matchLabels:
      app: epsfm
      stage: staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::045675425505:role/pixtavietnam-staging
      labels:
        app: epsfm
        stage: staging
