apiVersion: apps/v1
kind: Deployment
metadata:
  name: footage-resize-demand
  labels:
    app: footage-resize-demand
    stage: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: footage-resize-demand
      stage: production
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::045675425505:role/footage-resize-ec2-production
      labels:
        app: footage-resize-demand
        stage: production
    spec:
      containers:
        - name: footage-resize-demand
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/footage-resize:footage-ondemand-4.1.6-947
          imagePullPolicy: Always
