apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-product
  labels:
    app: worker-product
spec:
  selector:
    matchLabels:
      app: worker-product
  template:
    metadata:
      labels:
        app: worker-product
    spec:
      containers:
        - name: worker-product
          image: 045675425505.dkr.ecr.ap-northeast-1.amazonaws.com/worker-product:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: worker-product-common-env
            - secretRef:
                name: worker-product-secret
          resources:
            requests:
              memory: "4G"
              cpu: "2"
