apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider
spec:
  provider: aws
  secretObjects:
    - secretName: database-password
      type: Opaque
      data:
        - objectName: "DBSecret_eksworkshop"
          key: password
  parameters:
    objects: |
      - objectName: "DBSecret_eksworkshop"  # the AWS secret
        objectType: "secretsmanager"