apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secret-application
spec:
  provider: aws
  secretObjects:
    - secretName: application-api-key  # the k8s secret name
      type: Opaque
      data:
        - objectName: DBSecret_eksworkshop  # reference the corresponding parameter
          key: password
  parameters:
    objects: |
      - objectName: "DBSecret_eksworkshop"  # the AWS secret
        objectType: "secretsmanager"