apiVersion: v1
stringData:
    AIRBRAKE_PROJECT_ID: ENC[AES256_GCM,data:XV3nSRVS,iv:KgEKNcgACB7fmfBsiWVx/3jXpUu0OjmGHaW5VSwORRk=,tag:4bUq47wowiTISZZx4kYTIQ==,type:str]
    AIRBRAKE_PROJECT_KEY: ENC[AES256_GCM,data:z3qRBgwOErvnhaCdg2If2y7sKBvQ6NhxyNeicY9w3rI=,iv:bMeZSYBiJZ0PPrEHPbknssDPICnrxXXfkUVS4Hzlkgw=,tag:UIajFK91AZVdhIRctA/+bQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:jnbAVSt+/iWmd4k6evW5QIIm,iv:JLIrJYudkT4LJ5UyKia0qgbPxbbmKPJoocu/ubOumf4=,tag:K43sdr9SjW+jhfSJ3Fwu2A==,type:str]
    DB_NAME: ENC[AES256_GCM,data:YCJBtTMwftxR,iv:NOdWowX1xxmmePgfrzDa1iStVHYghaDaUyVRbUiNcko=,tag:g1Y1wBH7obteRqovCSW+TQ==,type:str]
    DB_PASS: ENC[AES256_GCM,data:yormidY8exZUWKjUvJdUuQ==,iv:kOIfzT+VIysODoas0Cc+jM9HrDbPEt4vA9UvApUE9FE=,tag:0oUHXkgzS7lkBJPvcsooig==,type:str]
    DB_USER: ENC[AES256_GCM,data:7fwGnarQrGCsaUg=,iv:DigW9itVtbMILDw2IWhi/PGSiyfZ1hSG/hhLefInBFk=,tag:VOQYQyHEGOJmPNn6UiGqRA==,type:str]
    DELAYED_JOB_PROCESS_NUM: ENC[AES256_GCM,data:RA==,iv:FGgOwNhyjDwlKoBETeEeDXlK1iLqB/IKgPaTZhVy0qM=,tag:oYNalz/ppZicXogBytePmA==,type:str]
    ELASTICSEARCH_GRANTED_USER: ENC[AES256_GCM,data:pVTC+RlDZW60CQ==,iv:W11YNHOtutkX3m4X55n8C3i6c45OHZ9wm+w5oojKoNM=,tag:Nvny/ygR3MvuJJzV+tmPYA==,type:str]
    ELASTICSEARCH_HOST: ENC[AES256_GCM,data:Y/EnlkOyJkurCQY33Y/8M/n1EyAs+XY2N1pyCRooIAo+SBBnYK8U8TFwAfT6ighpZXf8KicAk65PKU9/LDU68GjLlMM=,iv:mERk/Tv33DVU6Vphf9CmMfxSQgeAjic5WHlCYGEOa08=,tag:IInr2wPc4UL/cIPC1k21jg==,type:str]
    ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:xCpg+sCh,iv:ZeLMOR86tUhB1eJpQMNMDEcoBOEL9kQ8jw82527kPPc=,tag:MBGZKRuUfm95y8D5Si81vw==,type:str]
    ELASTICSEARCH_PHOTO_INDEX: ENC[AES256_GCM,data:FkPYVgZLngLm,iv:g6dKgekD4F8C/lsx6MD9in1n1ouAvLT4/GgN/3qUppw=,tag:TW1a4RDQvRt+gxX+DUafXQ==,type:str]
    ELASTICSEARCH_PHOTO_TYPE: ENC[AES256_GCM,data:r1RpL9ct7wU=,iv:oE1MOn9zwZm05qvniPVoidBrrQ7oTz4gL5VFPVClAY8=,tag:aglydoEe66W1HXX4pbbw1A==,type:str]
    ELASTICSEARCH_PORT: ENC[AES256_GCM,data:G2YuiA==,iv:1WYyWEkUueFUDV5xECdtfgjOlvnsO37fOhjXR7bTLS0=,tag:fGu2GL6QbghcXnJ762jFBA==,type:str]
    ELASTICSEARCH_SCHEME: ENC[AES256_GCM,data:BIxaEJc=,iv:sYlmf0ELLalPWTmhh64/IBi7z5+vDyiFO9c67oXCmKg=,tag:ePQmbsXPzULW8+tP75mO8Q==,type:str]
    HOST_NAME: ENC[AES256_GCM,data:3/Dawb4iIBhTTV9CEn40oUml779Ie9xyzhSw0TnzWqM6VWIKbw==,iv:1jDDEF/XEliA7yu6RGjF7OeNMMERA0y6DVJZmoprgRA=,tag:TsLEeAgwoa0AMtQzDidYPA==,type:str]
    PIXTA_TOKEN: ENC[AES256_GCM,data:JygKZHdN/8EiBRtS29Ik8XhCiPuN4mhV3RiGOILJn6Q=,iv:FXXgGIcunwV8iJ/T8nQ+TWcPGDqhrunLDu97O6F7g6o=,tag:VjzbmGBxqk3P+tTjdFLAkA==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:ErYXOrjST10UsanoWccQUV/kKsZu7SozVsa9qEmzFm+Qh5UPCe1V2hqUqGUm5Da7M2rZ6uSm7eWBe4IjjxKMnxNZZkGUq5iO8wDEbbwjjGabe00hgZHgjGo9PYvNA8UigjS8e8Cod/2jKra2DVRsrMdkQMPYgFTU0Sh1ZCC/MLM=,iv:gCtIrxNZWjj4cJUrMDllMju6sJsS0cHmiOQg5DXJixQ=,tag:XVD265RHySM4EPNzPBScoQ==,type:str]
    SLACK_NOTIFICATION_CHANNEL: ENC[AES256_GCM,data:fwT9hEpGUZMITQ1L,iv:4cF3Qner/xI121Ham8MXMHami+Y57jLqak3yk/bOvWs=,tag:zLU8EpCrvSwjyDDd87OPOA==,type:str]
    SLACK_NOTIFICATION_URL: ENC[AES256_GCM,data:J0uiihI7odr6BqjiJUmJPATjrxDtqB+NvFFMdD5fIF+I7mhYeK6+r1BZLwFUgf+dKB0L5OwRwJvGhrkT78/nzNtru45lsA9OK6h9v6o=,iv:iySl4phmvsMrIqwlEUI0EAsMPjzfUFn26yPKZ1qBOmk=,tag:7iUc461foQAQx50H5hLIJg==,type:str]
    ROLLBAR_ACCESS_TOKEN: ENC[AES256_GCM,data:+dDqjE7USyxQy4Lw5h+6+xJA0oFU76kw5VxMpnHLzAc=,iv:/JUku3if9ly8u3/pHKDNufY8UDKUtsV63N8ITmyqpTc=,tag:vwnD47BQkbFQ+AbfDS8moA==,type:str]
    IMS_WEBHOOK_TOKEN: ENC[AES256_GCM,data:7xtzkvXsARhzskGqyjLma5YYSJdezEuW2yWN4Bb2TOawqCH1ryeTAhnon+DOS4oy,iv:bf2c2tq9uZ+Hvuz0fCRA3ZQYyqAPbn86unNcRJnIg4k=,tag:A0cWsKmqt0DLO7wTp2QakQ==,type:str]
    IMAGE_SERVICE_API_KEY: ENC[AES256_GCM,data:5gpJ1xJmtahLv2CxFha2vpOodgSAoVKlFpk6IwWExUDsqAuE5xmilMDkIFInECLo,iv:gjUp086qYeqlw0lqd5/VdD7jQYVdwWY6ulotcfFtbLc=,tag:c5qNmak5xTqmeu3u/L/j0w==,type:str]
kind: Secret
metadata:
    name: pngfm-secret
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:045675425505:key/ee38c497-6147-4bd3-a58a-ea8c9845be7c
          created_at: "2022-10-11T06:58:44Z"
          enc: AQICAHhobnnncr8XFXX4QKWeGumP2AjuF/t1WTZdjh0ZfApr6QFIsXIhXq83vU0WKAscmYTzAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTcnH6a3ALJmtmJE7AgEQgDt+d+ONDjo7rxmgwd+OKI0BuhXdOrdnchlJiUSK0ecdrNt7HlhzsZhQVzpbIUHAO4UeNLECAZkmLbQgpg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-11T06:58:44Z"
    mac: ENC[AES256_GCM,data:L+6UzyOxXMVjoRAhnC7W/0YS57NuNQbYvlITMBg2m9VOlIDRm2ALAPnYXttPYq6Drvs8hTCoUuWGJQpCZ3lnjj1Lff9tIXkGmMX8bz4mC07Y76g1kGxakBo5RBzGRy7xlxTjsJwPFZ9uOZxK7Pq9fkRKUys4Ly5isxgRPROi230=,iv:wR4knkVzdKOaMvQfirAeG5xYFbCxMvBvga+t4OJpsEk=,tag:pDuVDNPfkzwbNWV9VgfoUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
